import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh-TW' | 'zh-CN' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    leaveRequests: 'Leave Requests',
    calendar: 'Calendar',
    profile: 'Profile',
    employees: 'Employees',
    reports: 'Reports',
    tasks: 'Tasks',
    cashControl: 'Cash Control',
    settings: 'Settings',
    staffProfile: 'Staff Profile',
    
    // Dashboard
    pendingRequests: 'Pending Requests',
    totalRequests: 'Total Requests',
    remainingDays: 'Remaining Days',
    usedDays: 'Used Days',
    daysRemaining: 'Days Remaining',
    daysUsed: 'Days Used',
    leaveBalance: 'Leave Balance',
    overview: 'Overview',
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',
    upcomingLeave: 'Upcoming Leave',
    teamOverview: 'Team Overview',
    
    // Leave Requests
    startDate: 'Start Date',
    endDate: 'End Date',
    leaveType: 'Leave Type',
    daysRequested: 'Days Requested',
    reason: 'Reason',
    status: 'Status',
    requestDate: 'Request Date',
    approve: 'Approve',
    reject: 'Reject',
    cancel: 'Cancel',
    submit: 'Submit',
    save: 'Save',
    close: 'Close',
    edit: 'Edit',
    delete: 'Delete',
    
    // Status Values
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    paid: 'Paid',
    seniorApproved: 'Senior Management Approved',
    
    // Leave Types
    annualLeave: 'Annual Leave',
    sickLeave: 'Sick Leave',
    maternityLeave: 'Maternity Leave',
    paternityLeave: 'Paternity Leave',
    vacation: 'Vacation',
    emergencyLeave: 'Emergency Leave',
    compassionateLeave: 'Compassionate Leave',
    studyLeave: 'Study Leave',
    unpaidLeave: 'Unpaid Leave',
    
    // View Modes
    myRequests: 'My Requests',
    teamRequests: 'Team Requests',
    allRequests: 'All Requests',
      myLeaveRequests: 'My Leave Requests',
      teamLeaveRequests: 'Team Leave Requests',
      requests: 'requests',
      overlappingLeaveRequest: 'Overlapping Leave Request',
      overlappingLeaveDescription: 'You already have a leave request for these dates. Please select different dates.',
      newRequest: 'New Request',
      confirmDeleteLeave: 'Delete Leave Request?',
      employee: 'Employee',
      actions: 'Actions',
    
    // Placeholders and Labels
    selectLeaveType: 'Select Leave Type',
    selectCategory: 'Select Category',
    selectType: 'Select Type',
    selectStatus: 'Select Status',
    allTypes: 'All Types',
    allStatus: 'All Status',
    searchPlaceholder: 'Search by employee name, reason...',
    searchByEmployeeReason: 'Search by employee or reason...',
    selectDate: 'Pick a date',
    submitLeaveRequestDescription: 'Submit a new leave request for approval',
    editRequestDescription: 'Edit your leave request details',
    confirmDeleteDescription: 'This action cannot be undone. This will permanently delete your leave request.',
    seniorApprove: 'Senior Approve',
    adminApprove: 'Admin Approve',
    finalApprove: 'Final Approve',
    noMatchingRequests: 'No requests match your current filters',
    clearFilters: 'Clear Filters',
    noLeaveRequestsFound: 'No leave requests found',
    max: 'Max',
    daysPerYear: 'days/year',
    
    // Actions
    createRequest: 'Create Request',
    editRequest: 'Edit Request',
    deleteRequest: 'Delete Request',
    confirmDelete: 'Confirm Delete',
    approveRequest: 'Approve Request',
    rejectRequest: 'Reject Request',
    update: 'Update',
    bulkActions: 'Bulk Actions',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    export: 'Export',
    print: 'Print',
    
    // Messages
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    loading: 'Loading...',
    noData: 'No Data',
    noResults: 'No Results',
    
    // Categories
    general: 'General',
    travel: 'Travel',
    meals: 'Meals',
    supplies: 'Supplies',
    equipment: 'Equipment',
    training: 'Training',
    groceries: 'Groceries',
    others: 'Others',
    officeSupplies: 'Office Supplies',
    
    // Transaction Types
    request: 'Request',
    expense: 'Expense',
    reimbursement: 'Reimbursement',
    
    // Cash Control
    cashControlTitle: 'Cash Control',
    cashControlDescription: 'Manage cash requests and expense reports',
    cashRequest: 'Cash Request',
    expenseReport: 'Expense Report',
    cashRequestTitle: 'Cash Request',
    cashRequestDescription: 'Request cash advance from the company',
    expenseReportTitle: 'Expense Report',
    expenseReportDescription: 'Submit an expense or reimbursement report',
    amount: 'Amount',
    currency: 'Currency',
    category: 'Category',
    description: 'Description',
    receipt: 'Receipt',
    uploadReceipt: 'Upload Receipt',
    uploading: 'Uploading...',
    receiptUploaded: 'Receipt uploaded successfully',
    enterReceiptUrl: 'Or enter receipt URL manually',
    cashBalance: 'Cash Balance',
    availableCashBalance: 'Available cash balance',
    credit: 'Credit',
    debit: 'Debit',
    balance: 'Balance',
    moneyReceived: 'Money received',
    moneySpent: 'Money spent',
    netPosition: 'Net position',
    recentTransactions: 'Recent Transactions',
    manageCashRequests: 'Manage cash requests and expense reports',
    yourCashHistory: 'Your cash transaction history',
    noTransactionsFound: 'No transactions found',
    affectsBalance: 'Affects Balance',
    rejectionReason: 'Reason',
    reasonForRejection: 'Reason for rejection:',
    cashRequestPlaceholder: 'Please explain why you need this cash advance...',
    cashRequestSuccess: 'Cash request submitted for approval',
    expenseReportSuccess: 'Expense report submitted successfully',
    transactionApproved: 'Transaction approved',
    transactionRejected: 'Transaction rejected',
    failedToApprove: 'Failed to approve transaction',
    failedToReject: 'Failed to reject transaction',
    failedToFetch: 'Failed to fetch transactions',
    failedToCreate: 'Failed to create cash request',
    failedToSubmit: 'Failed to submit expense report',
    receiptUploadSuccess: 'Receipt uploaded successfully',
    receiptUploadError: 'Failed to upload receipt',
    
    // Authentication
    signIn: 'Sign In',
    signOut: 'Sign Out',
    signUp: 'Sign Up',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password',
    resetPassword: 'Reset Password',
    
    // Profile page
    myProfile: 'My Profile',
    personalInformation: 'Personal Information',
    editProfile: 'Edit Profile',
    cancelEdit: 'Cancel',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    employeeId: 'Employee ID',
    department: 'Department',
    position: 'Position',
    selectDepartment: 'Select department',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    accountCreated: 'Account Created',
    leaveBalances: 'Leave Balances',
    report: 'Report',
    initialAllocation: 'Initial allocation',
    daysYear: 'days/year',
    used: 'Used',
    available: 'Available',
    noLeaveBalances: 'No leave balances configured for this year',
    profileNotFound: 'Profile not found',
    profileUpdateSuccess: 'Profile updated successfully',
    profileUpdateError: 'Failed to update profile',
    managePersonalInfo: 'Manage your personal information and view leave balances',
    
    // Leave Management
    leaveRequest: 'Leave Request',
    createLeaveRequest: 'Create Leave Request',
    submitLeaveRequest: 'Submit Leave Request',
    duration: 'Duration',
    day: 'Day',
    days: 'Days',
    reasonOptional: 'Reason (Optional)',
    reasonPlaceholder: 'Please provide a reason for your leave request...',
    requestSummary: 'Request Summary',
    submitting: 'Submitting...',
    requestSubmitted: 'Leave request submitted successfully',
    requestUpdated: 'Leave request updated successfully',
    requestDeleted: 'Leave request deleted successfully',
    endDateBeforeStart: 'End date cannot be before start date',
    overlappingDates: 'Leave dates overlap with an existing request',
    requiredField: 'Please fill in all required fields',
    operationFailed: 'Operation failed',
    
    // Department translations
    humanResources: 'Human Resources',
    engineering: 'Engineering',
    marketing: 'Marketing',
    sales: 'Sales',
    finance: 'Finance',
    operations: 'Operations',
    customerSupport: 'Customer Support',
    product: 'Product',
    legal: 'Legal',
    domesticHelper: 'Domestic Helper',
    unknown: 'Unknown',
    
    // Common actions
    add: 'Add',
    type: 'Type',
    requestStatus: 'Request status',
    
    // Calendar
    leaveCalendarDescription: 'View and manage leave requests on the calendar',
    calendarView: 'Calendar View',
    colorLegend: 'Color Legend',
    myLeave: 'My Leave',
    teamLeave: 'Team Leave',
    allLeave: 'All Leave',
    leaveAllocationManagement: 'Leave Allocation Management',
    showRestDays: 'Show rest days',
    showPublicHolidays: 'Show public holidays',
    restDays: 'Rest Days',
    publicHolidays: 'Public Holidays'
  },
  'zh-TW': {
    // Navigation
    dashboard: '儀表板',
    leaveRequests: '請假申請',
    calendar: '行事曆',
    profile: '個人資料',
    employees: '團隊管理',
    reports: '報告',
    tasks: '任務',
    cashControl: '現金管理',
    settings: '設定',
    staffProfile: '員工資料',
    
    // Dashboard
    pendingRequests: '待審核申請',
    totalRequests: '總申請數',
    remainingDays: '剩餘天數',
    usedDays: '已使用天數',
    daysRemaining: '剩餘天數',
    daysUsed: '已使用天數',
    leaveBalance: '休假餘額',
    overview: '概覽',
    quickActions: '快速操作',
    recentActivity: '最近活動',
    upcomingLeave: '即將到來的休假',
    teamOverview: '團隊概覽',
    
    // Leave Requests
    startDate: '開始日期',
    endDate: '結束日期',
    leaveType: '休假類型',
    daysRequested: '申請天數',
    reason: '原因',
    status: '狀態',
    requestDate: '申請日期',
    approve: '批准',
    reject: '拒絕',
    cancel: '取消',
    submit: '提交',
    save: '儲存',
    close: '關閉',
    edit: '編輯',
    delete: '刪除',
    
    // Status Values
    pending: '待審核',
    approved: '已批准',
    rejected: '已拒絕',
    paid: '已支付',
    seniorApproved: '高級管理層已批准',
    
    // Leave Types
    annualLeave: '年假',
    sickLeave: '病假',
    maternityLeave: '產假',
    paternityLeave: '陪產假',
    vacation: '休假',
    emergencyLeave: '緊急假',
    compassionateLeave: '恩恤假',
    studyLeave: '進修假',
    unpaidLeave: '無薪假',
    
    // View Modes
    myRequests: '我的申請',
    teamRequests: '團隊申請',
    allRequests: '所有申請',
      myLeaveRequests: '我的請假申請',
      teamLeaveRequests: '團隊請假申請',
      requests: '筆申請',
      overlappingLeaveRequest: '重疊的休假申請',
      overlappingLeaveDescription: '您在這些日期已有休假申請。請選擇不同的日期。',
      newRequest: '新申請',
      confirmDeleteLeave: '刪除休假申請？',
      employee: '員工',
      actions: '操作',
    
    // Placeholders and Labels
    selectLeaveType: '選擇休假類型',
    selectCategory: '選擇類別',
    selectType: '選擇類型',
    selectStatus: '選擇狀態',
    allTypes: '所有類型',
    allStatus: '所有狀態',
    searchPlaceholder: '按員工姓名、原因搜索...',
    searchByEmployeeReason: '按員工或原因搜尋...',
    selectDate: '選擇日期',
    submitLeaveRequestDescription: '提交新的請假申請以供審批',
    editRequestDescription: '編輯您的請假申請詳情',
    confirmDeleteDescription: '此操作無法撤銷。這將永久刪除您的請假申請。',
    seniorApprove: '高級管理層批准',
    adminApprove: '管理員批准',
    finalApprove: '最終批准',
    noMatchingRequests: '沒有符合當前篩選條件的申請',
    clearFilters: '清除篩選',
    noLeaveRequestsFound: '未找到請假申請',
    max: '最多',
    daysPerYear: '天/年',
    
    // Actions
    createRequest: '建立申請',
    editRequest: '編輯申請',
    deleteRequest: '刪除申請',
    confirmDelete: '確認刪除',
    approveRequest: '批准申請',
    rejectRequest: '拒絕申請',
    update: '更新',
    bulkActions: '批量操作',
    selectAll: '全選',
    deselectAll: '取消全選',
    export: '匯出',
    print: '列印',
    
    // Messages
    success: '成功',
    error: '錯誤',
    warning: '警告',
    info: '信息',
    loading: '載入中...',
    noData: '無數據',
    noResults: '無結果',
    
    // Categories
    general: '一般',
    travel: '差旅',
    meals: '餐費',
    supplies: '辦公用品',
    equipment: '設備',
    training: '培訓',
    groceries: '日用品',
    others: '其他',
    
    // Transaction Types
    request: '申請',
    expense: '支出',
    reimbursement: '報銷',
    
    // Cash Control
    cashControlTitle: '現金管理',
    cashControlDescription: '管理現金申請和報銷報告',
    cashRequest: '現金申請',
    expenseReport: '報銷報告',
    cashRequestTitle: '現金申請',
    cashRequestDescription: '向公司申請預支現金',
    expenseReportTitle: '報銷報告',
    expenseReportDescription: '提交報銷或退款報告',
    amount: '金額',
    currency: '貨幣',
    category: '類別',
    description: '說明',
    receipt: '收據',
    uploadReceipt: '上傳收據',
    uploading: '上傳中...',
    receiptUploaded: '收據上傳成功',
    enterReceiptUrl: '或手動輸入收據網址',
    cashBalance: '現金餘額',
    availableCashBalance: '可用現金餘額',
    credit: '收入',
    debit: '支出',
    balance: '餘額',
    moneyReceived: '已收金額',
    moneySpent: '已支出金額',
    netPosition: '淨額',
    recentTransactions: '最近交易',
    manageCashRequests: '管理現金申請和報銷報告',
    yourCashHistory: '您的現金交易記錄',
    noTransactionsFound: '未找到交易記錄',
    affectsBalance: '影響餘額',
    rejectionReason: '原因',
    reasonForRejection: '拒絕原因:',
    cashRequestPlaceholder: '請說明您需要此現金預支的原因...',
    cashRequestSuccess: '現金申請已提交待審核',
    expenseReportSuccess: '報銷報告已提交成功',
    transactionApproved: '交易已批准',
    transactionRejected: '交易已拒絕',
    failedToApprove: '批准交易失敗',
    failedToReject: '拒絕交易失敗',
    failedToFetch: '獲取交易記錄失敗',
    failedToCreate: '建立現金申請失敗',
    failedToSubmit: '提交報銷報告失敗',
    receiptUploadSuccess: '收據上傳成功',
    receiptUploadError: '上傳收據失敗',
    officeSupplies: '辦公用品',
    
    // Authentication
    signIn: '登入',
    signOut: '登出',
    signUp: '註冊',
    password: '密碼',
    confirmPassword: '確認密碼',
    forgotPassword: '忘記密碼',
    resetPassword: '重設密碼',
    
    // Profile page
    myProfile: '我的個人資料',
    personalInformation: '個人資訊',
    editProfile: '編輯個人資料',
    cancelEdit: '取消',
    firstName: '名字',
    lastName: '姓氏',
    email: '電子郵件',
    employeeId: '員工編號',
    department: '部門',
    position: '職位',
    selectDepartment: '選擇部門',
    saveChanges: '儲存變更',
    saving: '儲存中...',
    accountCreated: '帳戶建立日期',
    leaveBalances: '休假餘額',
    report: '報告',
    initialAllocation: '初始分配',
    daysYear: '天/年',
    used: '已使用',
    available: '可用',
    noLeaveBalances: '本年度未配置休假餘額',
    profileNotFound: '找不到個人資料',
    profileUpdateSuccess: '個人資料更新成功',
    profileUpdateError: '更新個人資料失敗',
    managePersonalInfo: '管理您的個人資訊並查看休假餘額',
    
    // Leave Management
    leaveRequest: '休假申請',
    createLeaveRequest: '建立休假申請',
    submitLeaveRequest: '提交休假申請',
    duration: '時間長度',
    day: '日',
    days: '天',
    reasonOptional: '原因（可選）',
    reasonPlaceholder: '請提供您的休假申請原因...',
    requestSummary: '申請摘要',
    submitting: '提交中...',
    requestSubmitted: '休假申請提交成功',
    requestUpdated: '休假申請更新成功',
    requestDeleted: '休假申請刪除成功',
    endDateBeforeStart: '結束日期不能早於開始日期',
    overlappingDates: '休假日期與現有申請重複',
    requiredField: '請填寫所有必填欄位',
    operationFailed: '操作失敗',
    
    // Department translations
    humanResources: '人力資源',
    engineering: '工程部',
    marketing: '行銷部',
    sales: '銷售部',
    finance: '財務部',
    operations: '營運部',
    customerSupport: '客戶支援',
    product: '產品部',
    legal: '法務部',
    domesticHelper: '家庭助理',
    unknown: '未知',
    
    // Common actions
    add: '新增',
    clear: '清除',
    search: '搜尋',
    type: '類型',
    requestStatus: '申請狀態',
    
    // Calendar
    leaveCalendarDescription: '在日曆上查看和管理休假申請',
    calendarView: '日曆視圖',
    colorLegend: '顏色圖例',
    myLeave: '我的休假',
    teamLeave: '團隊休假',
    allLeave: '所有休假',
    leaveAllocationManagement: '休假分配管理',
    showRestDays: '顯示休息日',
    showPublicHolidays: '顯示公眾假期',
    restDays: '休息日',
    publicHolidays: '公眾假期',
  },
  'zh-CN': {
    // Navigation
    dashboard: '仪表板',
    leaveRequests: '请假申请',
    calendar: '日历',
    profile: '个人资料',
    employees: '团队管理',
    reports: '报告',
    tasks: '任务',
    cashControl: '现金管理',
    settings: '设置',
    staffProfile: '员工资料',
    
    // Dashboard
    pendingRequests: '待审核申请',
    totalRequests: '总申请数',
    remainingDays: '剩余天数',
    usedDays: '已使用天数',
    daysRemaining: '剩余天数',
    daysUsed: '已使用天数',
    leaveBalance: '休假余额',
    overview: '概览',
    quickActions: '快速操作',
    recentActivity: '最近活动',
    upcomingLeave: '即将到来的休假',
    teamOverview: '团队概览',
    
    // Leave Requests
    startDate: '开始日期',
    endDate: '结束日期',
    leaveType: '休假类型',
    daysRequested: '申请天数',
    reason: '原因',
    status: '状态',
    requestDate: '申请日期',
    approve: '批准',
    reject: '拒绝',
    cancel: '取消',
    submit: '提交',
    save: '保存',
    close: '关闭',
    edit: '编辑',
    delete: '删除',
    
    // Status Values
    pending: '待审核',
    approved: '已批准',
    rejected: '已拒绝',
    paid: '已支付',
    seniorApproved: '高级管理层已批准',
    
    // Leave Types
    annualLeave: '年假',
    sickLeave: '病假',
    maternityLeave: '产假',
    paternityLeave: '陪产假',
    vacation: '休假',
    emergencyLeave: '紧急假',
    compassionateLeave: '恩恤假',
    studyLeave: '进修假',
    unpaidLeave: '无薪假',
    
    // View Modes
    myRequests: '我的申请',
    teamRequests: '团队申请',
    allRequests: '所有申请',
      myLeaveRequests: '我的请假申请',
      teamLeaveRequests: '团队请假申请',
      requests: '个申请',
      overlappingLeaveRequest: '重叠的休假申请',
      overlappingLeaveDescription: '您在这些日期已有休假申请。请选择不同的日期。',
      newRequest: '新申请',
      confirmDeleteLeave: '删除休假申请？',
      employee: '员工',
      actions: '操作',
    
    // Placeholders and Labels
    selectLeaveType: '选择休假类型',
    selectCategory: '选择类别',
    selectType: '选择类型',
    selectStatus: '选择状态',
    allTypes: '所有类型',
    allStatus: '所有状态',
    searchPlaceholder: '按员工姓名、原因搜索...',
    searchByEmployeeReason: '按员工或原因搜索...',
    selectDate: '选择日期',
    submitLeaveRequestDescription: '提交新的请假申请以供审批',
    editRequestDescription: '编辑您的请假申请详情',
    confirmDeleteDescription: '此操作无法撤销。这将永久删除您的请假申请。',
    seniorApprove: '高级管理层批准',
    adminApprove: '管理员批准',
    finalApprove: '最终批准',
    noMatchingRequests: '没有符合当前筛选条件的申请',
    clearFilters: '清除筛选',
    noLeaveRequestsFound: '未找到请假申请',
    max: '最多',
    daysPerYear: '天/年',
    
    // Actions
    createRequest: '创建申请',
    editRequest: '编辑申请',
    deleteRequest: '删除申请',
    confirmDelete: '确认删除',
    approveRequest: '批准申请',
    rejectRequest: '拒绝申请',
    update: '更新',
    bulkActions: '批量操作',
    selectAll: '全选',
    deselectAll: '取消全选',
    export: '导出',
    print: '打印',
    
    // Messages
    success: '成功',
    error: '错误',
    warning: '警告',
    info: '信息',
    loading: '加载中...',
    noData: '无数据',
    noResults: '无结果',
    
    // Categories
    general: '一般',
    travel: '差旅',
    meals: '餐费',
    supplies: '办公用品',
    equipment: '设备',
    training: '培训',
    groceries: '日用品',
    others: '其他',
    
    // Transaction Types
    request: '申请',
    expense: '支出',
    reimbursement: '报销',
    
    // Cash Control
    cashControlTitle: '现金管理',
    cashControlDescription: '管理现金申请和报销报告',
    cashRequest: '现金申请',
    expenseReport: '报销报告',
    cashRequestTitle: '现金申请',
    cashRequestDescription: '向公司申请预支现金',
    expenseReportTitle: '报销报告',
    expenseReportDescription: '提交报销或退款报告',
    amount: '金额',
    currency: '货币',
    category: '类别',
    description: '说明',
    receipt: '收据',
    uploadReceipt: '上传收据',
    uploading: '上传中...',
    receiptUploaded: '收据上传成功',
    enterReceiptUrl: '或手动输入收据网址',
    cashBalance: '现金余额',
    availableCashBalance: '可用现金余额',
    credit: '收入',
    debit: '支出',
    balance: '余额',
    moneyReceived: '已收金额',
    moneySpent: '已支出金额',
    netPosition: '净额',
    recentTransactions: '最近交易',
    manageCashRequests: '管理现金申请和报销报告',
    yourCashHistory: '您的现金交易记录',
    noTransactionsFound: '未找到交易记录',
    affectsBalance: '影响余额',
    rejectionReason: '原因',
    reasonForRejection: '拒绝原因:',
    cashRequestPlaceholder: '请说明您需要此现金预支的原因...',
    cashRequestSuccess: '现金申请已提交待审核',
    expenseReportSuccess: '报销报告已提交成功',
    transactionApproved: '交易已批准',
    transactionRejected: '交易已拒绝',
    failedToApprove: '批准交易失败',
    failedToReject: '拒绝交易失败',
    failedToFetch: '获取交易记录失败',
    failedToCreate: '建立现金申请失败',
    failedToSubmit: '提交报销报告失败',
    receiptUploadSuccess: '收据上传成功',
    receiptUploadError: '上传收据失败',
    officeSupplies: '办公用品',
    
    // Authentication
    signIn: '登录',
    signOut: '登出',
    signUp: '注册',
    password: '密码',
    confirmPassword: '确认密码',
    forgotPassword: '忘记密码',
    resetPassword: '重设密码',
    
    // Profile page
    myProfile: '我的个人资料',
    personalInformation: '个人信息',
    editProfile: '编辑个人资料',
    cancelEdit: '取消',
    firstName: '名字',
    lastName: '姓氏',
    email: '电子邮件',
    employeeId: '员工编号',
    department: '部门',
    position: '职位',
    selectDepartment: '选择部门',
    saveChanges: '保存更改',
    saving: '保存中...',
    accountCreated: '账户创建日期',
    leaveBalances: '休假余额',
    report: '报告',
    initialAllocation: '初始分配',
    daysYear: '天/年',
    used: '已使用',
    available: '可用',
    noLeaveBalances: '本年度未配置休假余额',
    profileNotFound: '找不到个人资料',
    profileUpdateSuccess: '个人资料更新成功',
    profileUpdateError: '更新个人资料失败',
    managePersonalInfo: '管理您的个人信息并查看休假余额',
    
    // Leave Management
    leaveRequest: '休假申请',
    createLeaveRequest: '创建休假申请',
    submitLeaveRequest: '提交休假申请',
    duration: '持续时间',
    day: '日',
    days: '天',
    reasonOptional: '原因（可选）',
    reasonPlaceholder: '请提供您的休假申请原因...',
    requestSummary: '申请摘要',
    submitting: '提交中...',
    requestSubmitted: '休假申请提交成功',
    requestUpdated: '休假申请更新成功',
    requestDeleted: '休假申请删除成功',
    endDateBeforeStart: '结束日期不能早于开始日期',
    overlappingDates: '休假日期与现有申请重叠',
    requiredField: '请填写所有必填字段',
    operationFailed: '操作失败',
    
    // Department translations
    humanResources: '人力资源',
    engineering: '工程部',
    marketing: '市场部',
    sales: '销售部',
    finance: '财务部',
    operations: '运营部',
    customerSupport: '客户支持',
    product: '产品部',
    legal: '法务部',
    domesticHelper: '家政助理',
    unknown: '未知',
    
    // Common actions
    add: '添加',
    clear: '清除',
    search: '搜索',
    type: '类型',
    requestStatus: '申请状态',
    
    // Calendar
    leaveCalendarDescription: '在日历上查看和管理休假申请',
    calendarView: '日历视图',
    colorLegend: '颜色图例',
    myLeave: '我的休假',
    teamLeave: '团队休假',
    allLeave: '所有休假',
    leaveAllocationManagement: '休假分配管理',
    showRestDays: '显示休息日',
    showPublicHolidays: '显示公众假期',
    restDays: '休息日',
    publicHolidays: '公众假期'
  },
  id: {
    // Navigation
    dashboard: 'Dasbor',
    leaveRequests: 'Permohonan Cuti',
    calendar: 'Kalender',
    profile: 'Profil',
    employees: 'Karyawan',
    reports: 'Laporan',
    tasks: 'Tugas',
    cashControl: 'Kontrol Kas',
    settings: 'Pengaturan',
    staffProfile: 'Profil Staf',
    
    // Dashboard
    pendingRequests: 'Permintaan Tertunda',
    totalRequests: 'Total Permintaan',
    remainingDays: 'Sisa Hari',
    usedDays: 'Hari Terpakai',
    daysRemaining: 'Sisa Hari',
    daysUsed: 'Hari Terpakai',
    leaveBalance: 'Saldo Cuti',
    overview: 'Ikhtisar',
    quickActions: 'Tindakan Cepat',
    recentActivity: 'Aktivitas Terbaru',
    upcomingLeave: 'Cuti Mendatang',
    teamOverview: 'Ikhtisar Tim',
    
    // Leave Requests
    startDate: 'Tanggal Mulai',
    endDate: 'Tanggal Berakhir',
    leaveType: 'Jenis Cuti',
    daysRequested: 'Hari yang Diminta',
    reason: 'Alasan',
    status: 'Status',
    requestDate: 'Tanggal Permintaan',
    approve: 'Setujui',
    reject: 'Tolak',
    cancel: 'Batal',
    submit: 'Kirim',
    save: 'Simpan',
    close: 'Tutup',
    edit: 'Edit',
    delete: 'Hapus',
    
    // Status Values
    pending: 'Menunggu',
    approved: 'Disetujui',
    rejected: 'Ditolak',
    paid: 'Dibayar',
    seniorApproved: 'Disetujui Manajemen Senior',
    
    // Leave Types
    annualLeave: 'Cuti Tahunan',
    sickLeave: 'Cuti Sakit',
    maternityLeave: 'Cuti Melahirkan',
    paternityLeave: 'Cuti Ayah',
    vacation: 'Liburan',
    emergencyLeave: 'Cuti Darurat',
    compassionateLeave: 'Cuti Duka',
    studyLeave: 'Cuti Belajar',
    unpaidLeave: 'Cuti Tanpa Gaji',
    
    // View Modes
    myRequests: 'Permintaan Saya',
    teamRequests: 'Permintaan Tim',
    allRequests: 'Semua Permintaan',
      myLeaveRequests: 'Permohonan Cuti Saya',
      teamLeaveRequests: 'Permohonan Cuti Tim',
      requests: 'permintaan',
      overlappingLeaveRequest: 'Permintaan Cuti Tumpang Tindih',
      overlappingLeaveDescription: 'Anda sudah memiliki permintaan cuti untuk tanggal-tanggal ini. Silakan pilih tanggal yang berbeda.',
      newRequest: 'Permintaan Baru',
      confirmDeleteLeave: 'Hapus Permintaan Cuti?',
      employee: 'Karyawan',
      actions: 'Tindakan',
    
    // Placeholders and Labels
    selectLeaveType: 'Pilih Jenis Cuti',
    selectCategory: 'Pilih Kategori',
    selectType: 'Pilih Jenis',
    selectStatus: 'Pilih Status',
    allTypes: 'Semua Jenis',
    allStatus: 'Semua Status',
    searchPlaceholder: 'Cari berdasarkan nama karyawan, alasan...',
    searchByEmployeeReason: 'Cari berdasarkan karyawan atau alasan...',
    selectDate: 'Pilih tanggal',
    submitLeaveRequestDescription: 'Kirim permintaan cuti baru untuk persetujuan',
    editRequestDescription: 'Edit detail permintaan cuti Anda',
    confirmDeleteDescription: 'Tindakan ini tidak dapat dibatalkan. Ini akan menghapus permintaan cuti Anda secara permanen.',
    seniorApprove: 'Persetujuan Senior',
    adminApprove: 'Persetujuan Admin',
    finalApprove: 'Persetujuan Final',
    noMatchingRequests: 'Tidak ada permintaan yang cocok dengan filter saat ini',
    clearFilters: 'Hapus Filter',
    noLeaveRequestsFound: 'Tidak ada permintaan cuti ditemukan',
    max: 'Maks',
    daysPerYear: 'hari/tahun',
    
    // Actions
    createRequest: 'Buat Permintaan',
    editRequest: 'Edit Permintaan',
    deleteRequest: 'Hapus Permintaan',
    confirmDelete: 'Konfirmasi Hapus',
    approveRequest: 'Setujui Permintaan',
    rejectRequest: 'Tolak Permintaan',
    update: 'Perbarui',
    bulkActions: 'Tindakan Massal',
    selectAll: 'Pilih Semua',
    deselectAll: 'Batalkan Pilihan',
    export: 'Ekspor',
    print: 'Cetak',
    
    // Messages
    success: 'Sukses',
    error: 'Error',
    warning: 'Peringatan',
    info: 'Info',
    loading: 'Memuat...',
    noData: 'Tidak Ada Data',
    noResults: 'Tidak Ada Hasil',
    
    // Categories
    general: 'Umum',
    travel: 'Perjalanan',
    meals: 'Makanan',
    supplies: 'Perlengkapan Kantor',
    equipment: 'Peralatan',
    training: 'Pelatihan',
    groceries: 'Bahan Makanan',
    others: 'Lainnya',
    
    // Transaction Types
    request: 'Permintaan',
    expense: 'Pengeluaran',
    reimbursement: 'Penggantian',
    
    // Cash Control
    cashControlTitle: 'Kontrol Kas',
    cashControlDescription: 'Kelola permintaan kas dan laporan pengeluaran',
    cashRequest: 'Permintaan Kas',
    expenseReport: 'Laporan Pengeluaran',
    cashRequestTitle: 'Permintaan Kas',
    cashRequestDescription: 'Ajukan uang muka dari perusahaan',
    expenseReportTitle: 'Laporan Pengeluaran',
    expenseReportDescription: 'Ajukan laporan pengeluaran atau penggantian',
    amount: 'Jumlah',
    currency: 'Mata Uang',
    category: 'Kategori',
    description: 'Deskripsi',
    receipt: 'Tanda Terima',
    uploadReceipt: 'Unggah Tanda Terima',
    uploading: 'Mengunggah...',
    receiptUploaded: 'Tanda terima berhasil diunggah',
    enterReceiptUrl: 'Atau masukkan URL tanda terima secara manual',
    cashBalance: 'Saldo Kas',
    availableCashBalance: 'Saldo kas yang tersedia',
    credit: 'Kredit',
    debit: 'Debit',
    balance: 'Saldo',
    moneyReceived: 'Uang diterima',
    moneySpent: 'Uang dibelanjakan',
    netPosition: 'Posisi bersih',
    recentTransactions: 'Transaksi Terkini',
    manageCashRequests: 'Kelola permintaan kas dan laporan pengeluaran',
    yourCashHistory: 'Riwayat transaksi kas Anda',
    noTransactionsFound: 'Tidak ada transaksi ditemukan',
    affectsBalance: 'Mempengaruhi Saldo',
    rejectionReason: 'Alasan',
    reasonForRejection: 'Alasan penolakan:',
    cashRequestPlaceholder: 'Jelaskan mengapa Anda memerlukan uang muka ini...',
    cashRequestSuccess: 'Permintaan kas diajukan untuk persetujuan',
    expenseReportSuccess: 'Laporan pengeluaran berhasil diajukan',
    transactionApproved: 'Transaksi disetujui',
    transactionRejected: 'Transaksi ditolak',
    failedToApprove: 'Gagal menyetujui transaksi',
    failedToReject: 'Gagal menolak transaksi',
    failedToFetch: 'Gagal mengambil transaksi',
    failedToCreate: 'Gagal membuat permintaan kas',
    failedToSubmit: 'Gagal mengirim laporan pengeluaran',
    receiptUploadSuccess: 'Tanda terima berhasil diunggah',
    receiptUploadError: 'Gagal mengunggah tanda terima',
    officeSupplies: 'Perlengkapan Kantor',
    
    // Authentication
    signIn: 'Masuk',
    signOut: 'Keluar',
    signUp: 'Daftar',
    password: 'Kata Sandi',
    confirmPassword: 'Konfirmasi Kata Sandi',
    forgotPassword: 'Lupa Kata Sandi',
    resetPassword: 'Reset Kata Sandi',
    
    // Profile page
    myProfile: 'Profil Saya',
    personalInformation: 'Informasi Pribadi',
    editProfile: 'Edit Profil',
    cancelEdit: 'Batal',
    firstName: 'Nama Depan',
    lastName: 'Nama Belakang',
    email: 'Email',
    employeeId: 'ID Karyawan',
    department: 'Departemen',
    position: 'Posisi',
    selectDepartment: 'Pilih departemen',
    saveChanges: 'Simpan Perubahan',
    saving: 'Menyimpan...',
    accountCreated: 'Akun Dibuat',
    leaveBalances: 'Saldo Cuti',
    report: 'Laporan',
    initialAllocation: 'Alokasi awal',
    daysYear: 'hari/tahun',
    used: 'Digunakan',
    available: 'Tersedia',
    noLeaveBalances: 'Tidak ada saldo cuti yang dikonfigurasi untuk tahun ini',
    profileNotFound: 'Profil tidak ditemukan',
    profileUpdateSuccess: 'Profil berhasil diperbarui',
    profileUpdateError: 'Gagal memperbarui profil',
    managePersonalInfo: 'Kelola informasi pribadi Anda dan lihat saldo cuti',
    
    // Leave Management
    leaveRequest: 'Cuti',
    createLeaveRequest: 'Buat Permohonan Cuti',
    submitLeaveRequest: 'Kirim Permohonan Cuti',
    duration: 'Durasi',
    day: 'Hari',
    days: 'Hari',
    reasonOptional: 'Alasan (Opsional)',
    reasonPlaceholder: 'Silakan berikan alasan untuk permohonan cuti Anda...',
    requestSummary: 'Ringkasan Permohonan',
    submitting: 'Mengirim...',
    requestSubmitted: 'Permohonan cuti berhasil dikirim',
    requestUpdated: 'Permohonan cuti berhasil diperbarui',
    requestDeleted: 'Permohonan cuti berhasil dihapus',
    endDateBeforeStart: 'Tanggal berakhir tidak boleh sebelum tanggal mulai',
    overlappingDates: 'Tanggal cuti bertumpang tindih dengan permohonan yang sudah ada',
    requiredField: 'Harap isi semua field yang wajib diisi',
    operationFailed: 'Operasi gagal',
    
    // Department translations
    humanResources: 'Sumber Daya Manusia',
    engineering: 'Teknik',
    marketing: 'Pemasaran',
    sales: 'Penjualan',
    finance: 'Keuangan',
    operations: 'Operasional',
    customerSupport: 'Dukungan Pelanggan',
    product: 'Produk',
    legal: 'Hukum',
    domesticHelper: 'Asisten Rumah Tangga',
    unknown: 'Tidak Diketahui',
    
    // Common actions
    add: 'Tambah',
    clear: 'Bersihkan',
    search: 'Cari',
    type: 'Jenis',
    requestStatus: 'Status permintaan',
    
    // Calendar
    leaveCalendarDescription: 'Lihat dan kelola permohonan cuti di kalender',
    calendarView: 'Tampilan Kalender',
    colorLegend: 'Legenda Warna',
    myLeave: 'Cuti Saya',
    teamLeave: 'Cuti Tim',
    allLeave: 'Semua Cuti',
    leaveAllocationManagement: 'Manajemen Alokasi Cuti',
    showRestDays: 'Tampilkan hari istirahat',
    showPublicHolidays: 'Tampilkan hari libur umum',
    restDays: 'Hari Istirahat',
    publicHolidays: 'Hari Libur Umum'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'zh-TW', 'zh-CN', 'id'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};