import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh-TW' | 'zh-CN' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    leaveRequests: 'Leave Requests',
    calendar: 'Calendar',
    profile: 'Profile',
    employees: 'Employees',
    reports: 'Reports',
    tasks: 'Tasks',
    cashControl: 'Cash Control',
    settings: 'Settings',
    staffProfile: 'Staff Profile',
    
    // Dashboard
    welcomeBack: 'Welcome Back!',
    dashboardSubtitle: "Manage your leave requests and stay updated with your team's schedule",
    pendingRequests: 'Pending Requests',
    totalRequests: 'Total Requests',
    totalThisYear: 'Total This Year',
    remainingDays: 'Remaining Days',
    usedDays: 'Used Days',
    daysRemaining: 'Days Remaining',
    daysUsed: 'Days Used',
    leaveBalance: 'Leave Balance',
    leaveBalanceDetails: 'Leave Balance Details',
    myLeaveBalance: 'My Leave Balance',
    teamLeaveOverview: 'Team Leave Overview',
    overview: 'Overview',
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',
    upcomingLeave: 'Upcoming Leave',
    teamOverview: 'Team Overview',
    remaining: 'Remaining',
    of: 'of',
    noLeaveAllocations: 'No leave allocations found for this year',
    // Dashboard card descriptions
    manageLeaveRequestsDescription: 'Submit and manage your leave requests',
    dashboardCalendarDescription: 'View leave calendar and upcoming time off',
    updatePersonalInfoDescription: 'Update your personal information',
    manageTeamRequestsDescription: "Manage your team's leave requests",
    viewLeaveReportsDescription: 'View comprehensive leave reports',
    // Profile Requests card
    myProfileRequests: 'My Profile Requests',
    profileChangeRequests: 'Profile Change Requests',
    yourProfileChangeRequests: 'Your profile change requests',
    teamProfileChangeRequests: 'Team profile change requests',
    // Landing
    leaveManagementSystem: 'Leave Management System',
    landingSubtitle: "Streamline your organization's leave management process",
    getStarted: 'Get Started',
    secureEfficientEasy: 'Secure • Efficient • Easy to Use',
    
    // Leave Requests
    startDate: 'Start Date',
    endDate: 'End Date',
    leaveType: 'Leave Type',
    daysRequested: 'Days Requested',
    reason: 'Reason',
    status: 'Status',
    requestDate: 'Request Date',
    approve: 'Approve',
    reject: 'Reject',
    cancel: 'Cancel',
    submit: 'Submit',
    save: 'Save',
    close: 'Close',
    edit: 'Edit',
    delete: 'Delete',
    
    // Status Values
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    paid: 'Paid',
    seniorApproved: 'Senior Management Approved',
    
    // Leave Types
    annualLeave: 'Annual Leave',
    sickLeave: 'Sick Leave',
    maternityLeave: 'Maternity Leave',
    paternityLeave: 'Paternity Leave',
    vacation: 'Vacation',
    emergencyLeave: 'Emergency Leave',
    compassionateLeave: 'Compassionate Leave',
    studyLeave: 'Study Leave',
    unpaidLeave: 'Unpaid Leave',
    
    // View Modes
    myRequests: 'My Requests',
    teamRequests: 'Team Requests',
    allRequests: 'All Requests',
      myLeaveRequests: 'My Leave Requests',
      teamLeaveRequests: 'Team Leave Requests',
      requests: 'requests',
      overlappingLeaveRequest: 'Overlapping Leave Request',
      overlappingLeaveDescription: 'You already have a leave request for these dates. Please select different dates.',
      newRequest: 'New Request',
      confirmDeleteLeave: 'Delete Leave Request?',
      employee: 'Employee',
      actions: 'Actions',
    
    // Placeholders and Labels
    selectLeaveType: 'Select Leave Type',
    selectCategory: 'Select Category',
    selectType: 'Select Type',
    selectStatus: 'Select Status',
    allTypes: 'All Types',
    allStatus: 'All Status',
    searchPlaceholder: 'Search by employee name, reason...',
    searchByEmployeeReason: 'Search by employee or reason...',
    selectDate: 'Pick a date',
    submitLeaveRequestDescription: 'Submit a new leave request for approval',
    editRequestDescription: 'Edit your leave request details',
    confirmDeleteDescription: 'This action cannot be undone. This will permanently delete your leave request.',
    seniorApprove: 'Senior Approve',
    adminApprove: 'Admin Approve',
    finalApprove: 'Final Approve',
    noMatchingRequests: 'No requests match your current filters',
    clearFilters: 'Clear Filters',
    noLeaveRequestsFound: 'No leave requests found',
    max: 'Max',
    daysPerYear: 'days/year',
    
    // Actions
    createRequest: 'Create Request',
    editRequest: 'Edit Request',
    deleteRequest: 'Delete Request',
    confirmDelete: 'Confirm Delete',
    approveRequest: 'Approve Request',
    rejectRequest: 'Reject Request',
    update: 'Update',
    bulkActions: 'Bulk Actions',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    export: 'Export',
    exportSuccess: 'Data exported successfully',
    print: 'Print',
    
    // Messages
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    loading: 'Loading...',
    noData: 'No Data',
    noResults: 'No Results',
    
    // Categories
    general: 'General',
    travel: 'Travel',
    meals: 'Meals',
    supplies: 'Supplies',
    equipment: 'Equipment',
    training: 'Training',
    groceries: 'Groceries',
    others: 'Others',
    officeSupplies: 'Office Supplies',
    
    // Transaction Types
    request: 'Request',
    expense: 'Expense',
    reimbursement: 'Reimbursement',
    
    // Cash Control
    cashControlTitle: 'Cash Control',
    cashControlDescription: 'Manage cash requests and expense reports',
    newTransaction: 'New Transaction',
    cashRequest: 'Cash Request',
    expenseReport: 'Expense Report',
    cashRequestTitle: 'Cash Request',
    cashRequestDescription: 'Request cash advance from the company',
    expenseReportTitle: 'Expense Report',
    expenseReportDescription: 'Submit an expense or reimbursement report',
    amount: 'Amount',
    currency: 'Currency',
    category: 'Category',
    description: 'Description',
    receipt: 'Receipt',
    uploadReceipt: 'Upload Receipt',
    uploading: 'Uploading...',
    receiptUploaded: 'Receipt uploaded successfully',
    enterReceiptUrl: 'Or enter receipt URL manually',
    cashBalance: 'Cash Balance',
    availableCashBalance: 'Available cash balance',
    credit: 'Credit',
    debit: 'Debit',
    balance: 'Balance',
    moneyReceived: 'Money received',
    moneySpent: 'Money spent',
    netPosition: 'Net position',
    recentTransactions: 'Recent Transactions',
    manageCashRequests: 'Manage cash requests and expense reports',
    yourCashHistory: 'Your cash transaction history',
    noTransactionsFound: 'No transactions found',
    affectsBalance: 'Affects Balance',
    rejectionReason: 'Reason',
    reasonForRejection: 'Reason for rejection:',
    cashRequestPlaceholder: 'Please explain why you need this cash advance...',
    cashRequestSuccess: 'Cash request submitted for approval',
    expenseReportSuccess: 'Expense report submitted successfully',
    transactionApproved: 'Transaction approved',
    transactionRejected: 'Transaction rejected',
    failedToApprove: 'Failed to approve transaction',
    failedToReject: 'Failed to reject transaction',
    failedToFetch: 'Failed to fetch transactions',
    failedToCreate: 'Failed to create cash request',
    failedToSubmit: 'Failed to submit expense report',
    receiptUploadSuccess: 'Receipt uploaded successfully',
    receiptUploadError: 'Failed to upload receipt',
    
    // Authentication
    signIn: 'Sign In',
    signOut: 'Sign Out',
    signUp: 'Sign Up',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password',
    resetPassword: 'Reset Password',
    
    // Profile page
    myProfile: 'My Profile',
    personalInformation: 'Personal Information',
    editProfile: 'Edit Profile',
    cancelEdit: 'Cancel',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    employeeId: 'Employee ID',
    department: 'Department',
    position: 'Position',
    phoneNumber: 'Phone Number',
    dateOfBirth: 'Date of Birth',
    idNumber: 'ID Number',
    passportNumber: 'Passport Number',
    visaNumber: 'Visa Number',
    maritalStatus: 'Marital Status',
    emergencyContactName: 'Emergency Contact Name',
    emergencyContactPhone: 'Emergency Contact Phone',
    homeAddress: 'Home Address',
    selectDepartment: 'Select department',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    accountCreated: 'Account Created',
    leaveBalances: 'Leave Balances',
    report: 'Report',
    comingSoon: 'Coming Soon',
    reportFeatureComingSoon: 'The report generation feature will be available soon. It will allow you to download a detailed PDF report of your leave balances.',
    initialAllocation: 'Initial allocation',
    daysYear: 'days/year',
    used: 'Used',
    available: 'Available',
    noLeaveBalances: 'No leave balances configured for this year',
    profileNotFound: 'Profile not found',
    profileUpdateSuccess: 'Profile updated successfully',
    profileUpdateError: 'Failed to update profile',
    managePersonalInfo: 'Manage your personal information and view leave balances',
    personalDetails: 'Personal Details',
    requestChange: 'Request Change',
    accountEmailLogin: 'Account Email (Login)',
    enterLastName: 'Enter last name',
    enterEmailAddress: 'Enter email address',
    enterEmployeeId: 'Enter employee ID',
    selectDepartmentPlaceholder: 'Select department',
    enterPosition: 'Enter position/job title',
    enterPhoneNumber: 'Enter phone number or NIL if not applicable',
    enterDateOfBirth: 'Enter date of birth or NIL if not applicable',
    enterIdNumber: 'Enter ID number or NIL if not applicable',
    enterPassportNumber: 'Enter passport number or NIL if not applicable',
    enterVisaNumber: 'Enter visa number or NIL if not applicable',
    selectMaritalStatus: 'Select marital status',
    enterEmergencyContactName: 'Enter emergency contact name or NIL if not applicable',
    enterEmergencyContactPhone: 'Enter emergency contact phone or NIL if not applicable',
    enterHomeAddress: 'Enter home address or NIL if not applicable',
    notProvided: 'Not provided',
    submitRequest: 'Submit Request',
    requestProfileChange: 'Request Profile Change',
    submitRequestDescription: 'Submit a request to change profile information that requires approval.',
    selectFieldToChange: 'Select field to change',
    selectField: 'Select field',
    enterNewValue: 'Enter new value',
    fromTo: 'From: "{from}" → To: "{to}"',
    
    // Documents
    documents: 'Documents',
    uploadDocument: 'Upload Document',
    uploadDocumentDescription: 'Upload a new document for this profile',
    documentType: 'Document Type',
    selectDocumentType: 'Select document type',
    file: 'File',
    selected: 'Selected',
    documentUploaded: 'Document uploaded successfully',
    documentDeleted: 'Document deleted successfully',
    deleteDocument: 'Delete Document',
    deleteDocumentConfirm: 'Are you sure you want to delete this document? This action cannot be undone.',
    noDocuments: 'No documents uploaded yet',
    passport: 'Passport',
    idCard: 'ID Card',
    visa: 'Visa',
    certificate: 'Certificate',
    contract: 'Contract',
    document: 'Document',
    
    // Leave Management
    leaveRequest: 'Leave Request',
    createLeaveRequest: 'Create Leave Request',
    submitLeaveRequest: 'Submit Leave Request',
    duration: 'Duration',
    day: 'Day',
    days: 'Days',
    reasonOptional: 'Reason (Optional)',
    reasonPlaceholder: 'Please provide a reason for your leave request...',
    requestSummary: 'Request Summary',
    submitting: 'Submitting...',
    requestSubmitted: 'Leave request submitted successfully',
    requestUpdated: 'Leave request updated successfully',
    requestDeleted: 'Leave request deleted successfully',
    endDateBeforeStart: 'End date cannot be before start date',
    overlappingDates: 'Leave dates overlap with an existing request',
    requiredField: 'Please fill in all required fields',
    operationFailed: 'Operation failed',
    
    // Department translations
    humanResources: 'Human Resources',
    engineering: 'Engineering',
    marketing: 'Marketing',
    sales: 'Sales',
    finance: 'Finance',
    operations: 'Operations',
    customerSupport: 'Customer Support',
    product: 'Product',
    legal: 'Legal',
    domesticHelper: 'Domestic Helper',
    unknown: 'Unknown',
    
    // Common actions
    add: 'Add',
    type: 'Type',
    requestStatus: 'Request status',
    
    // Calendar
    leaveCalendarDescription: 'View and manage leave requests on the calendar',
    calendarView: 'Calendar View',
    colorLegend: 'Color Legend',
    myLeave: 'My Leave',
    teamLeave: 'Team Leave',
    allLeave: 'All Leave',
    leaveAllocationManagement: 'Leave Allocation Management',
    showRestDays: 'Show rest days',
    showPublicHolidays: 'Show public holidays',
    restDays: 'Rest Days',
    publicHolidays: 'Public Holidays',

    // Tasks
    manageTasks: 'Manage tasks and assignments',
    createTask: 'Create Task',
    selectTeamMember: 'Select team member',
    noTasksFound: 'No tasks found',
    start: 'Start',
    complete: 'Complete',

    // Task Status
    inProgress: 'In Progress',
    completed: 'Completed',
    cancelled: 'Cancelled',

    // Priority
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',
    
    // Roles
    roleEmployee: 'Employee',
    roleHrAdmin: 'HR Admin',
    roleAdministrator: 'Administrator',
    roleManager: 'Manager',
    
    // Settings Page
    administratorSettings: 'Administrator Settings',
    manageSystemSettings: 'Manage system settings and role delegation',
    delegation: 'Delegation',
    leaveManagement: 'Leave Management',
    workSchedules: 'Work Schedules',
    storageCentre: 'Storage Centre',
    
    // Delegation Settings
    delegationManagement: 'Delegation Management',
    seniorManagementDelegation: 'Senior Management Delegation',
    delegationDescription: 'When enabled, Senior Management can execute final approvals for leave requests and allocations without requiring Administrator confirmation.',
    roleHierarchyPermissions: 'Role Hierarchy & Permissions',
    administratorCompanyOwner: 'Administrator / Company Owner',
    highestAuthority: 'Highest authority with unrestricted access to all system modules and data',
    seniorManagementHRGM: 'Senior Management (HR/GM)',
    firstLineExecutor: 'First-line executor for employee processes, manages onboarding and approval workflows',
    twoTierApprovalSystem: 'Two-Tier Approval System',
    leaveAllocationsRequire: 'Leave allocations require Senior Management approval first, then Administrator confirmation',
    leaveRequestsFollow: 'Leave requests follow the same dual approval workflow',
    administratorCanDelegate: 'Administrator can delegate final approval rights to Senior Management',
    administratorRetains: 'Administrator retains the right to review and override any decision',
    hrAdminRoleManagement: 'HR Admin Role Management',
    currentHRAdministrators: 'Current HR Administrators',
    noHRAdminsAssigned: 'No HR Admins assigned',
    demoteToEmployee: 'Demote to Employee',
    promoteEmployeeToHRAdmin: 'Promote Employee to HR Admin',
    selectAnEmployee: 'Select an employee...',
    promoteToHRAdmin: 'Promote to HR Admin',
    delegationEnabledSuccess: 'Delegation enabled successfully',
    delegationDisabledSuccess: 'Delegation disabled successfully',
    employeePromotedSuccess: 'Employee promoted to HR Admin successfully',
    hrAdminDemotedSuccess: 'HR Admin demoted to Employee successfully',
    failedToFetchDelegationSettings: 'Failed to fetch delegation settings',
    failedToUpdateDelegationSettings: 'Failed to update delegation settings',
    failedToFetchHRAdmins: 'Failed to fetch HR admins',
    failedToFetchEmployees: 'Failed to fetch employees',
    failedToPromoteEmployee: 'Failed to promote employee',
    failedToDemoteHRAdmin: 'Failed to demote HR admin',
    onlyHRAdminsCanManage: 'Only HR Admins and Administrators can manage delegation settings.'
  },
  'zh-TW': {
    // Navigation
    dashboard: '儀表板',
    leaveRequests: '請假申請',
    calendar: '行事曆',
    profile: '個人資料',
    employees: '團隊管理',
    reports: '報告',
    tasks: '任務',
    cashControl: '現金管理',
    settings: '設定',
    staffProfile: '員工資料',
    
    // Dashboard
    welcomeBack: '歡迎回來！',
    dashboardSubtitle: '管理您的請假申請並掌握團隊行程',
    pendingRequests: '待審核申請',
    totalRequests: '總申請數',
    totalThisYear: '本年度總計',
    remainingDays: '剩餘天數',
    usedDays: '已使用天數',
    daysRemaining: '剩餘天數',
    daysUsed: '已使用天數',
    leaveBalance: '休假餘額',
    leaveBalanceDetails: '休假餘額明細',
    myLeaveBalance: '我的休假餘額',
    teamLeaveOverview: '團隊休假概覽',
    overview: '概覽',
    quickActions: '快速操作',
    recentActivity: '最近活動',
    upcomingLeave: '即將到來的休假',
    teamOverview: '團隊概覽',
    remaining: '剩餘',
    of: '的',
    noLeaveAllocations: '今年沒有假期分配',
    // Dashboard card descriptions
    manageLeaveRequestsDescription: '提交及管理您的請假申請',
    dashboardCalendarDescription: '查看行事曆與即將到來的休假',
    updatePersonalInfoDescription: '更新您的個人資料',
    manageTeamRequestsDescription: '管理您的團隊請假申請',
    viewLeaveReportsDescription: '查看完整的請假報告',
    // Profile Requests card
    myProfileRequests: '我的資料變更申請',
    profileChangeRequests: '資料變更申請',
    yourProfileChangeRequests: '您的資料變更申請',
    teamProfileChangeRequests: '團隊資料變更申請',
    // Landing
    leaveManagementSystem: '請假管理系統',
    landingSubtitle: '讓您的組織請假流程更順暢',
    getStarted: '開始使用',
    secureEfficientEasy: '安全 • 高效 • 易用',
    
    // Leave Requests
    startDate: '開始日期',
    endDate: '結束日期',
    leaveType: '休假類型',
    daysRequested: '申請天數',
    reason: '原因',
    status: '狀態',
    requestDate: '申請日期',
    approve: '批准',
    reject: '拒絕',
    cancel: '取消',
    submit: '提交',
    save: '儲存',
    close: '關閉',
    edit: '編輯',
    delete: '刪除',
    
    // Status Values
    pending: '待審核',
    approved: '已批准',
    rejected: '已拒絕',
    paid: '已支付',
    seniorApproved: '高級管理層已批准',
    
    // Leave Types
    annualLeave: '年假',
    sickLeave: '病假',
    maternityLeave: '產假',
    paternityLeave: '陪產假',
    vacation: '休假',
    emergencyLeave: '緊急假',
    compassionateLeave: '恩恤假',
    studyLeave: '進修假',
    unpaidLeave: '無薪假',
    
    // View Modes
    myRequests: '我的申請',
    teamRequests: '團隊申請',
    allRequests: '所有申請',
      myLeaveRequests: '我的請假申請',
      teamLeaveRequests: '團隊請假申請',
      requests: '筆申請',
      overlappingLeaveRequest: '重疊的休假申請',
      overlappingLeaveDescription: '您在這些日期已有休假申請。請選擇不同的日期。',
      newRequest: '新申請',
      confirmDeleteLeave: '刪除休假申請？',
      employee: '員工',
      actions: '操作',
    
    // Placeholders and Labels
    selectLeaveType: '選擇休假類型',
    selectCategory: '選擇類別',
    selectType: '選擇類型',
    selectStatus: '選擇狀態',
    allTypes: '所有類型',
    allStatus: '所有狀態',
    searchPlaceholder: '按員工姓名、原因搜索...',
    searchByEmployeeReason: '按員工或原因搜尋...',
    selectDate: '選擇日期',
    submitLeaveRequestDescription: '提交新的請假申請以供審批',
    editRequestDescription: '編輯您的請假申請詳情',
    confirmDeleteDescription: '此操作無法撤銷。這將永久刪除您的請假申請。',
    seniorApprove: '高級管理層批准',
    adminApprove: '管理員批准',
    finalApprove: '最終批准',
    noMatchingRequests: '沒有符合當前篩選條件的申請',
    clearFilters: '清除篩選',
    noLeaveRequestsFound: '未找到請假申請',
    max: '最多',
    daysPerYear: '天/年',
    
    // Actions
    createRequest: '建立申請',
    editRequest: '編輯申請',
    deleteRequest: '刪除申請',
    confirmDelete: '確認刪除',
    approveRequest: '批准申請',
    rejectRequest: '拒絕申請',
    update: '更新',
    bulkActions: '批量操作',
    selectAll: '全選',
    deselectAll: '取消全選',
    export: '匯出',
    exportSuccess: '數據匯出成功',
    print: '列印',
    
    // Messages
    success: '成功',
    error: '錯誤',
    warning: '警告',
    info: '信息',
    loading: '載入中...',
    noData: '無數據',
    noResults: '無結果',
    
    // Categories
    general: '一般',
    travel: '差旅',
    meals: '餐費',
    supplies: '辦公用品',
    equipment: '設備',
    training: '培訓',
    groceries: '日用品',
    others: '其他',
    
    // Transaction Types
    request: '申請',
    expense: '支出',
    reimbursement: '報銷',
    
    // Cash Control
    cashControlTitle: '現金管理',
    cashControlDescription: '管理現金申請和報銷報告',
    newTransaction: '新交易',
    cashRequest: '現金申請',
    expenseReport: '報銷報告',
    cashRequestTitle: '現金申請',
    cashRequestDescription: '向公司申請預支現金',
    expenseReportTitle: '報銷報告',
    expenseReportDescription: '提交報銷或退款報告',
    amount: '金額',
    currency: '貨幣',
    category: '類別',
    description: '說明',
    receipt: '收據',
    uploadReceipt: '上傳收據',
    uploading: '上傳中...',
    receiptUploaded: '收據上傳成功',
    enterReceiptUrl: '或手動輸入收據網址',
    cashBalance: '現金餘額',
    availableCashBalance: '可用現金餘額',
    credit: '收入',
    debit: '支出',
    balance: '餘額',
    moneyReceived: '已收金額',
    moneySpent: '已支出金額',
    netPosition: '淨額',
    recentTransactions: '最近交易',
    manageCashRequests: '管理現金申請和報銷報告',
    yourCashHistory: '您的現金交易記錄',
    noTransactionsFound: '未找到交易記錄',
    affectsBalance: '影響餘額',
    rejectionReason: '原因',
    reasonForRejection: '拒絕原因:',
    cashRequestPlaceholder: '請說明您需要此現金預支的原因...',
    cashRequestSuccess: '現金申請已提交待審核',
    expenseReportSuccess: '報銷報告已提交成功',
    transactionApproved: '交易已批准',
    transactionRejected: '交易已拒絕',
    failedToApprove: '批准交易失敗',
    failedToReject: '拒絕交易失敗',
    failedToFetch: '獲取交易記錄失敗',
    failedToCreate: '建立現金申請失敗',
    failedToSubmit: '提交報銷報告失敗',
    receiptUploadSuccess: '收據上傳成功',
    receiptUploadError: '上傳收據失敗',
    officeSupplies: '辦公用品',
    
    // Authentication
    signIn: '登入',
    signOut: '登出',
    signUp: '註冊',
    password: '密碼',
    confirmPassword: '確認密碼',
    forgotPassword: '忘記密碼',
    resetPassword: '重設密碼',
    
    // Profile page
    myProfile: '我的個人資料',
    personalInformation: '個人資訊',
    editProfile: '編輯個人資料',
    cancelEdit: '取消',
    firstName: '名字',
    lastName: '姓氏',
    email: '電子郵件',
    employeeId: '員工編號',
    department: '部門',
    position: '職位',
    phoneNumber: '電話號碼',
    dateOfBirth: '出生日期',
    idNumber: '身份證號碼',
    passportNumber: '護照號碼',
    visaNumber: '簽證號碼',
    maritalStatus: '婚姻狀況',
    emergencyContactName: '緊急聯絡人姓名',
    emergencyContactPhone: '緊急聯絡人電話',
    homeAddress: '家庭住址',
    selectDepartment: '選擇部門',
    saveChanges: '儲存變更',
    saving: '儲存中...',
    accountCreated: '帳戶建立日期',
    leaveBalances: '休假餘額',
    report: '報告',
    comingSoon: '即將推出',
    reportFeatureComingSoon: '報告生成功能即將推出。您將能夠下載休假餘額的詳細PDF報告。',
    initialAllocation: '初始分配',
    daysYear: '天/年',
    used: '已使用',
    available: '可用',
    noLeaveBalances: '本年度未配置休假餘額',
    profileNotFound: '找不到個人資料',
    profileUpdateSuccess: '個人資料更新成功',
    profileUpdateError: '更新個人資料失敗',
    managePersonalInfo: '管理您的個人資訊並查看休假餘額',
    personalDetails: '個人詳情',
    requestChange: '申請變更',
    accountEmailLogin: '帳戶電子郵件（登入）',
    enterLastName: '輸入姓氏',
    enterEmailAddress: '輸入電子郵件地址',
    enterEmployeeId: '輸入員工編號',
    selectDepartmentPlaceholder: '選擇部門',
    enterPosition: '輸入職位/職稱',
    enterPhoneNumber: '輸入電話號碼或輸入 NIL 如不適用',
    enterDateOfBirth: '輸入出生日期或輸入 NIL 如不適用',
    enterIdNumber: '輸入身份證號碼或輸入 NIL 如不適用',
    enterPassportNumber: '輸入護照號碼或輸入 NIL 如不適用',
    enterVisaNumber: '輸入簽證號碼或輸入 NIL 如不適用',
    selectMaritalStatus: '選擇婚姻狀況',
    enterEmergencyContactName: '輸入緊急聯絡人姓名或輸入 NIL 如不適用',
    enterEmergencyContactPhone: '輸入緊急聯絡人電話或輸入 NIL 如不適用',
    enterHomeAddress: '輸入家庭住址或輸入 NIL 如不適用',
    notProvided: '未提供',
    submitRequest: '提交申請',
    requestProfileChange: '申請資料變更',
    submitRequestDescription: '提交申請以變更需要批准的個人資料。',
    selectFieldToChange: '選擇要變更的欄位',
    selectField: '選擇欄位',
    enterNewValue: '輸入新值',
    fromTo: '從："{from}" → 到："{to}"',
    
    // Documents
    documents: '文件',
    uploadDocument: '上傳文件',
    uploadDocumentDescription: '為此個人檔案上傳新文件',
    documentType: '文件類型',
    selectDocumentType: '選擇文件類型',
    file: '檔案',
    selected: '已選擇',
    documentUploaded: '文件上傳成功',
    documentDeleted: '文件刪除成功',
    deleteDocument: '刪除文件',
    deleteDocumentConfirm: '您確定要刪除此文件嗎？此操作無法撤銷。',
    noDocuments: '尚未上傳文件',
    passport: '護照',
    idCard: '身份證',
    visa: '簽證',
    certificate: '證書',
    contract: '合約',
    document: '文件',
    
    // Leave Management
    leaveRequest: '休假申請',
    createLeaveRequest: '建立休假申請',
    submitLeaveRequest: '提交休假申請',
    duration: '時間長度',
    day: '日',
    days: '天',
    reasonOptional: '原因（可選）',
    reasonPlaceholder: '請提供您的休假申請原因...',
    requestSummary: '申請摘要',
    submitting: '提交中...',
    requestSubmitted: '休假申請提交成功',
    requestUpdated: '休假申請更新成功',
    requestDeleted: '休假申請刪除成功',
    endDateBeforeStart: '結束日期不能早於開始日期',
    overlappingDates: '休假日期與現有申請重複',
    requiredField: '請填寫所有必填欄位',
    operationFailed: '操作失敗',
    
    // Department translations
    humanResources: '人力資源',
    engineering: '工程部',
    marketing: '行銷部',
    sales: '銷售部',
    finance: '財務部',
    operations: '營運部',
    customerSupport: '客戶支援',
    product: '產品部',
    legal: '法務部',
    domesticHelper: '家庭助理',
    unknown: '未知',
    
    // Common actions
    add: '新增',
    clear: '清除',
    search: '搜尋',
    type: '類型',
    requestStatus: '申請狀態',
    
    // Calendar
    leaveCalendarDescription: '在日曆上查看和管理休假申請',
    calendarView: '日曆視圖',
    colorLegend: '顏色圖例',
    myLeave: '我的休假',
    teamLeave: '團隊休假',
    allLeave: '所有休假',
    leaveAllocationManagement: '休假分配管理',
    showRestDays: '顯示休息日',
    showPublicHolidays: '顯示公眾假期',
    restDays: '休息日',
    publicHolidays: '公眾假期',

    // 任務
    manageTasks: '管理任務與派工',
    createTask: '建立任務',
    selectTeamMember: '選擇團隊成員',
    noTasksFound: '未找到任務',
    start: '開始',
    complete: '完成',

    // 任務狀態
    inProgress: '進行中',
    completed: '已完成',
    cancelled: '已取消',

    // 優先順序
    low: '低',
    medium: '中',
    high: '高',
    urgent: '緊急',
    
    // 角色
    roleEmployee: '員工',
    roleHrAdmin: '人力資源管理員',
    roleAdministrator: '系統管理員',
    roleManager: '經理',
    
    // Settings Page
    administratorSettings: '管理員設定',
    manageSystemSettings: '管理系統設定和角色委派',
    delegation: '委派',
    leaveManagement: '休假管理',
    workSchedules: '工作時間表',
    storageCentre: '文件中心',
    
    // Delegation Settings
    delegationManagement: '委派管理',
    seniorManagementDelegation: '高級管理層委派',
    delegationDescription: '啟用後，高級管理層可以執行最終批准請假申請和分配，無需管理員確認。',
    roleHierarchyPermissions: '角色層級與權限',
    administratorCompanyOwner: '管理員 / 公司所有者',
    highestAuthority: '最高權限，可訪問所有系統模組和數據',
    seniorManagementHRGM: '高級管理層（人力資源/總經理）',
    firstLineExecutor: '員工流程的第一線執行者，管理入職和審批流程',
    twoTierApprovalSystem: '兩級審批系統',
    leaveAllocationsRequire: '休假分配需要先經過高級管理層批准，然後由管理員確認',
    leaveRequestsFollow: '休假申請遵循相同的雙重審批流程',
    administratorCanDelegate: '管理員可以委派最終批准權給高級管理層',
    administratorRetains: '管理員保留審查和否決任何決定的權利',
    hrAdminRoleManagement: '人力資源管理員角色管理',
    currentHRAdministrators: '當前人力資源管理員',
    noHRAdminsAssigned: '未分配人力資源管理員',
    demoteToEmployee: '降級為員工',
    promoteEmployeeToHRAdmin: '將員工提升為人力資源管理員',
    selectAnEmployee: '選擇員工...',
    promoteToHRAdmin: '提升為人力資源管理員',
    delegationEnabledSuccess: '委派已成功啟用',
    delegationDisabledSuccess: '委派已成功停用',
    employeePromotedSuccess: '員工已成功提升為人力資源管理員',
    hrAdminDemotedSuccess: '人力資源管理員已成功降級為員工',
    failedToFetchDelegationSettings: '獲取委派設定失敗',
    failedToUpdateDelegationSettings: '更新委派設定失敗',
    failedToFetchHRAdmins: '獲取人力資源管理員失敗',
    failedToFetchEmployees: '獲取員工失敗',
    failedToPromoteEmployee: '提升員工失敗',
    failedToDemoteHRAdmin: '降級人力資源管理員失敗',
    onlyHRAdminsCanManage: '只有人力資源管理員和系統管理員可以管理委派設定。'
  },
  'zh-CN': {
    // Navigation
    dashboard: '仪表板',
    leaveRequests: '请假申请',
    calendar: '日历',
    profile: '个人资料',
    employees: '团队管理',
    reports: '报告',
    tasks: '任务',
    cashControl: '现金管理',
    settings: '设置',
    staffProfile: '员工资料',
    
    // Dashboard
    welcomeBack: '欢迎回来！',
    dashboardSubtitle: '管理您的请假申请并掌握团队日程',
    pendingRequests: '待审核申请',
    totalRequests: '总申请数',
    totalThisYear: '本年度总计',
    remainingDays: '剩余天数',
    usedDays: '已使用天数',
    daysRemaining: '剩余天数',
    daysUsed: '已使用天数',
    leaveBalance: '休假余额',
    leaveBalanceDetails: '休假余额明细',
    myLeaveBalance: '我的休假余额',
    teamLeaveOverview: '团队休假概览',
    overview: '概览',
    quickActions: '快速操作',
    recentActivity: '最近活动',
    upcomingLeave: '即将到来的休假',
    teamOverview: '团队概览',
    remaining: '剩余',
    of: '的',
    noLeaveAllocations: '今年没有假期分配',
    // Dashboard card descriptions
    manageLeaveRequestsDescription: '提交并管理您的请假申请',
    dashboardCalendarDescription: '查看日历及即将到来的休假',
    updatePersonalInfoDescription: '更新您的个人资料',
    manageTeamRequestsDescription: '管理您的团队请假申请',
    viewLeaveReportsDescription: '查看全面的请假报表',
    // Profile Requests card
    myProfileRequests: '我的资料变更申请',
    profileChangeRequests: '资料变更申请',
    yourProfileChangeRequests: '您的资料变更申请',
    teamProfileChangeRequests: '团队资料变更申请',
    // Landing
    leaveManagementSystem: '请假管理系统',
    landingSubtitle: '让您的组织请假流程更顺畅',
    getStarted: '开始使用',
    secureEfficientEasy: '安全 • 高效 • 易用',
    
    // Leave Requests
    startDate: '开始日期',
    endDate: '结束日期',
    leaveType: '休假类型',
    daysRequested: '申请天数',
    reason: '原因',
    status: '状态',
    requestDate: '申请日期',
    approve: '批准',
    reject: '拒绝',
    cancel: '取消',
    submit: '提交',
    save: '保存',
    close: '关闭',
    edit: '编辑',
    delete: '删除',
    
    // Status Values
    pending: '待审核',
    approved: '已批准',
    rejected: '已拒绝',
    paid: '已支付',
    seniorApproved: '高级管理层已批准',
    
    // Leave Types
    annualLeave: '年假',
    sickLeave: '病假',
    maternityLeave: '产假',
    paternityLeave: '陪产假',
    vacation: '休假',
    emergencyLeave: '紧急假',
    compassionateLeave: '恩恤假',
    studyLeave: '进修假',
    unpaidLeave: '无薪假',
    
    // View Modes
    myRequests: '我的申请',
    teamRequests: '团队申请',
    allRequests: '所有申请',
      myLeaveRequests: '我的请假申请',
      teamLeaveRequests: '团队请假申请',
      requests: '个申请',
      overlappingLeaveRequest: '重叠的休假申请',
      overlappingLeaveDescription: '您在这些日期已有休假申请。请选择不同的日期。',
      newRequest: '新申请',
      confirmDeleteLeave: '删除休假申请？',
      employee: '员工',
      actions: '操作',
    
    // Placeholders and Labels
    selectLeaveType: '选择休假类型',
    selectCategory: '选择类别',
    selectType: '选择类型',
    selectStatus: '选择状态',
    allTypes: '所有类型',
    allStatus: '所有状态',
    searchPlaceholder: '按员工姓名、原因搜索...',
    searchByEmployeeReason: '按员工或原因搜索...',
    selectDate: '选择日期',
    submitLeaveRequestDescription: '提交新的请假申请以供审批',
    editRequestDescription: '编辑您的请假申请详情',
    confirmDeleteDescription: '此操作无法撤销。这将永久删除您的请假申请。',
    seniorApprove: '高级管理层批准',
    adminApprove: '管理员批准',
    finalApprove: '最终批准',
    noMatchingRequests: '没有符合当前筛选条件的申请',
    clearFilters: '清除筛选',
    noLeaveRequestsFound: '未找到请假申请',
    max: '最多',
    daysPerYear: '天/年',
    
    // Actions
    createRequest: '创建申请',
    editRequest: '编辑申请',
    deleteRequest: '删除申请',
    confirmDelete: '确认删除',
    approveRequest: '批准申请',
    rejectRequest: '拒绝申请',
    update: '更新',
    bulkActions: '批量操作',
    selectAll: '全选',
    deselectAll: '取消全选',
    export: '导出',
    exportSuccess: '数据导出成功',
    print: '打印',
    
    // Messages
    success: '成功',
    error: '错误',
    warning: '警告',
    info: '信息',
    loading: '加载中...',
    noData: '无数据',
    noResults: '无结果',
    
    // Categories
    general: '一般',
    travel: '差旅',
    meals: '餐费',
    supplies: '办公用品',
    equipment: '设备',
    training: '培训',
    groceries: '日用品',
    others: '其他',
    
    // Transaction Types
    request: '申请',
    expense: '支出',
    reimbursement: '报销',
    
    // Cash Control
    cashControlTitle: '现金管理',
    cashControlDescription: '管理现金申请和报销报告',
    newTransaction: '新交易',
    cashRequest: '现金申请',
    expenseReport: '报销报告',
    cashRequestTitle: '现金申请',
    cashRequestDescription: '向公司申请预支现金',
    expenseReportTitle: '报销报告',
    expenseReportDescription: '提交报销或退款报告',
    amount: '金额',
    currency: '货币',
    category: '类别',
    description: '说明',
    receipt: '收据',
    uploadReceipt: '上传收据',
    uploading: '上传中...',
    receiptUploaded: '收据上传成功',
    enterReceiptUrl: '或手动输入收据网址',
    cashBalance: '现金余额',
    availableCashBalance: '可用现金余额',
    credit: '收入',
    debit: '支出',
    balance: '余额',
    moneyReceived: '已收金额',
    moneySpent: '已支出金额',
    netPosition: '净额',
    recentTransactions: '最近交易',
    manageCashRequests: '管理现金申请和报销报告',
    yourCashHistory: '您的现金交易记录',
    noTransactionsFound: '未找到交易记录',
    affectsBalance: '影响余额',
    rejectionReason: '原因',
    reasonForRejection: '拒绝原因:',
    cashRequestPlaceholder: '请说明您需要此现金预支的原因...',
    cashRequestSuccess: '现金申请已提交待审核',
    expenseReportSuccess: '报销报告已提交成功',
    transactionApproved: '交易已批准',
    transactionRejected: '交易已拒绝',
    failedToApprove: '批准交易失败',
    failedToReject: '拒绝交易失败',
    failedToFetch: '获取交易记录失败',
    failedToCreate: '建立现金申请失败',
    failedToSubmit: '提交报销报告失败',
    receiptUploadSuccess: '收据上传成功',
    receiptUploadError: '上传收据失败',
    officeSupplies: '办公用品',
    
    // Authentication
    signIn: '登录',
    signOut: '登出',
    signUp: '注册',
    password: '密码',
    confirmPassword: '确认密码',
    forgotPassword: '忘记密码',
    resetPassword: '重设密码',
    
    // Profile page
    myProfile: '我的个人资料',
    personalInformation: '个人信息',
    editProfile: '编辑个人资料',
    cancelEdit: '取消',
    firstName: '名字',
    lastName: '姓氏',
    email: '电子邮件',
    employeeId: '员工编号',
    department: '部门',
    position: '职位',
    phoneNumber: '电话号码',
    dateOfBirth: '出生日期',
    idNumber: '身份证号码',
    passportNumber: '护照号码',
    visaNumber: '签证号码',
    maritalStatus: '婚姻状况',
    emergencyContactName: '紧急联系人姓名',
    emergencyContactPhone: '紧急联系人电话',
    homeAddress: '家庭住址',
    selectDepartment: '选择部门',
    saveChanges: '保存更改',
    saving: '保存中...',
    accountCreated: '账户创建日期',
    leaveBalances: '休假余额',
    report: '报告',
    comingSoon: '即将推出',
    reportFeatureComingSoon: '报告生成功能即将推出。您将能够下载休假余额的详细PDF报告。',
    initialAllocation: '初始分配',
    daysYear: '天/年',
    used: '已使用',
    available: '可用',
    noLeaveBalances: '本年度未配置休假余额',
    profileNotFound: '找不到个人资料',
    profileUpdateSuccess: '个人资料更新成功',
    profileUpdateError: '更新个人资料失败',
    managePersonalInfo: '管理您的个人信息并查看休假余额',
    personalDetails: '个人详情',
    requestChange: '申请变更',
    accountEmailLogin: '账户电子邮件（登录）',
    enterLastName: '输入姓氏',
    enterEmailAddress: '输入电子邮件地址',
    enterEmployeeId: '输入员工编号',
    selectDepartmentPlaceholder: '选择部门',
    enterPosition: '输入职位/职称',
    enterPhoneNumber: '输入电话号码或输入 NIL 如不适用',
    enterDateOfBirth: '输入出生日期或输入 NIL 如不适用',
    enterIdNumber: '输入身份证号码或输入 NIL 如不适用',
    enterPassportNumber: '输入护照号码或输入 NIL 如不适用',
    enterVisaNumber: '输入签证号码或输入 NIL 如不适用',
    selectMaritalStatus: '选择婚姻状况',
    enterEmergencyContactName: '输入紧急联系人姓名或输入 NIL 如不适用',
    enterEmergencyContactPhone: '输入紧急联系人电话或输入 NIL 如不适用',
    enterHomeAddress: '输入家庭住址或输入 NIL 如不适用',
    notProvided: '未提供',
    submitRequest: '提交申请',
    requestProfileChange: '申请资料变更',
    submitRequestDescription: '提交申请以变更需要批准的个人资料。',
    selectFieldToChange: '选择要变更的栏位',
    selectField: '选择栏位',
    enterNewValue: '输入新值',
    fromTo: '从："{from}" → 到："{to}"',
    
    // Documents
    documents: '文件',
    uploadDocument: '上传文件',
    uploadDocumentDescription: '为此个人档案上传新文件',
    documentType: '文件类型',
    selectDocumentType: '选择文件类型',
    file: '文件',
    selected: '已选择',
    documentUploaded: '文件上传成功',
    documentDeleted: '文件删除成功',
    deleteDocument: '删除文件',
    deleteDocumentConfirm: '您确定要删除此文件吗？此操作无法撤销。',
    noDocuments: '尚未上传文件',
    passport: '护照',
    idCard: '身份证',
    visa: '签证',
    certificate: '证书',
    contract: '合约',
    document: '文件',
    
    // Leave Management
    leaveRequest: '休假申请',
    createLeaveRequest: '创建休假申请',
    submitLeaveRequest: '提交休假申请',
    duration: '持续时间',
    day: '日',
    days: '天',
    reasonOptional: '原因（可选）',
    reasonPlaceholder: '请提供您的休假申请原因...',
    requestSummary: '申请摘要',
    submitting: '提交中...',
    requestSubmitted: '休假申请提交成功',
    requestUpdated: '休假申请更新成功',
    requestDeleted: '休假申请删除成功',
    endDateBeforeStart: '结束日期不能早于开始日期',
    overlappingDates: '休假日期与现有申请重叠',
    requiredField: '请填写所有必填字段',
    operationFailed: '操作失败',
    
    // Department translations
    humanResources: '人力资源',
    engineering: '工程部',
    marketing: '市场部',
    sales: '销售部',
    finance: '财务部',
    operations: '运营部',
    customerSupport: '客户支持',
    product: '产品部',
    legal: '法务部',
    domesticHelper: '家政助理',
    unknown: '未知',
    
    // Common actions
    add: '添加',
    clear: '清除',
    search: '搜索',
    type: '类型',
    requestStatus: '申请状态',
    
    // Calendar
    leaveCalendarDescription: '在日历上查看和管理休假申请',
    calendarView: '日历视图',
    colorLegend: '颜色图例',
    myLeave: '我的休假',
    teamLeave: '团队休假',
    allLeave: '所有休假',
    leaveAllocationManagement: '休假分配管理',
    showRestDays: '显示休息日',
    showPublicHolidays: '显示公众假期',
    restDays: '休息日',
    publicHolidays: '公众假期',

    // 任务
    manageTasks: '管理任务与指派',
    createTask: '创建任务',
    selectTeamMember: '选择团队成员',
    noTasksFound: '未找到任务',
    start: '开始',
    complete: '完成',

    // 任务状态
    inProgress: '进行中',
    completed: '已完成',
    cancelled: '已取消',

    // 优先级
    low: '低',
    medium: '中',
    high: '高',
    urgent: '紧急',
    
    // 角色
    roleEmployee: '员工',
    roleHrAdmin: '人力资源管理员',
    roleAdministrator: '系统管理员',
    roleManager: '经理',
    
    // Settings Page
    administratorSettings: '管理员设置',
    manageSystemSettings: '管理系统设置和角色委派',
    delegation: '委派',
    leaveManagement: '休假管理',
    workSchedules: '工作时间表',
    storageCentre: '文件中心',
    
    // Delegation Settings
    delegationManagement: '委派管理',
    seniorManagementDelegation: '高级管理层委派',
    delegationDescription: '启用后，高级管理层可以执行最终批准休假申请和分配，无需管理员确认。',
    roleHierarchyPermissions: '角色层级与权限',
    administratorCompanyOwner: '管理员 / 公司所有者',
    highestAuthority: '最高权限，可访问所有系统模块和数据',
    seniorManagementHRGM: '高级管理层（人力资源/总经理）',
    firstLineExecutor: '员工流程的第一线执行者，管理入职和审批流程',
    twoTierApprovalSystem: '两级审批系统',
    leaveAllocationsRequire: '休假分配需要先经过高级管理层批准，然后由管理员确认',
    leaveRequestsFollow: '休假申请遵循相同的双重审批流程',
    administratorCanDelegate: '管理员可以委派最终批准权给高级管理层',
    administratorRetains: '管理员保留审查和否决任何决定的权利',
    hrAdminRoleManagement: '人力资源管理员角色管理',
    currentHRAdministrators: '当前人力资源管理员',
    noHRAdminsAssigned: '未分配人力资源管理员',
    demoteToEmployee: '降级为员工',
    promoteEmployeeToHRAdmin: '将员工提升为人力资源管理员',
    selectAnEmployee: '选择员工...',
    promoteToHRAdmin: '提升为人力资源管理员',
    delegationEnabledSuccess: '委派已成功启用',
    delegationDisabledSuccess: '委派已成功停用',
    employeePromotedSuccess: '员工已成功提升为人力资源管理员',
    hrAdminDemotedSuccess: '人力资源管理员已成功降级为员工',
    failedToFetchDelegationSettings: '获取委派设置失败',
    failedToUpdateDelegationSettings: '更新委派设置失败',
    failedToFetchHRAdmins: '获取人力资源管理员失败',
    failedToFetchEmployees: '获取员工失败',
    failedToPromoteEmployee: '提升员工失败',
    failedToDemoteHRAdmin: '降级人力资源管理员失败',
    onlyHRAdminsCanManage: '只有人力资源管理员和系统管理员可以管理委派设置。'
  },
  id: {
    // Navigation
    dashboard: 'Dasbor',
    leaveRequests: 'Permohonan Cuti',
    calendar: 'Kalender',
    profile: 'Profil',
    employees: 'Karyawan',
    reports: 'Laporan',
    tasks: 'Tugas',
    cashControl: 'Kontrol Kas',
    settings: 'Pengaturan',
    staffProfile: 'Profil Staf',
    
    // Dashboard
    welcomeBack: 'Selamat datang kembali!',
    dashboardSubtitle: 'Kelola permintaan cuti dan pantau jadwal tim Anda',
    pendingRequests: 'Permintaan Tertunda',
    totalRequests: 'Total Permintaan',
    totalThisYear: 'Total Tahun Ini',
    remainingDays: 'Sisa Hari',
    usedDays: 'Hari Terpakai',
    daysRemaining: 'Sisa Hari',
    daysUsed: 'Hari Terpakai',
    leaveBalance: 'Saldo Cuti',
    leaveBalanceDetails: 'Rincian Saldo Cuti',
    myLeaveBalance: 'Saldo Cuti Saya',
    teamLeaveOverview: 'Ikhtisar Cuti Tim',
    overview: 'Ikhtisar',
    quickActions: 'Tindakan Cepat',
    recentActivity: 'Aktivitas Terbaru',
    upcomingLeave: 'Cuti Mendatang',
    teamOverview: 'Ikhtisar Tim',
    remaining: 'Sisa',
    of: 'dari',
    noLeaveAllocations: 'Tidak ada alokasi cuti untuk tahun ini',
    // Dashboard card descriptions
    manageLeaveRequestsDescription: 'Ajukan dan kelola permintaan cuti Anda',
    dashboardCalendarDescription: 'Lihat kalender cuti dan waktu libur yang akan datang',
    updatePersonalInfoDescription: 'Perbarui informasi pribadi Anda',
    manageTeamRequestsDescription: 'Kelola permintaan cuti tim Anda',
    viewLeaveReportsDescription: 'Lihat laporan cuti yang komprehensif',
    // Profile Requests card
    myProfileRequests: 'Permintaan Profil Saya',
    profileChangeRequests: 'Permintaan Perubahan Profil',
    yourProfileChangeRequests: 'Permintaan perubahan profil Anda',
    teamProfileChangeRequests: 'Permintaan perubahan profil tim',
    // Landing
    leaveManagementSystem: 'Sistem Manajemen Cuti',
    landingSubtitle: 'Permudah proses manajemen cuti organisasi Anda',
    getStarted: 'Mulai',
    secureEfficientEasy: 'Aman • Efisien • Mudah digunakan',
    
    // Leave Requests
    startDate: 'Tanggal Mulai',
    endDate: 'Tanggal Berakhir',
    leaveType: 'Jenis Cuti',
    daysRequested: 'Hari yang Diminta',
    reason: 'Alasan',
    status: 'Status',
    requestDate: 'Tanggal Permintaan',
    approve: 'Setujui',
    reject: 'Tolak',
    cancel: 'Batal',
    submit: 'Kirim',
    save: 'Simpan',
    close: 'Tutup',
    edit: 'Edit',
    delete: 'Hapus',
    
    // Status Values
    pending: 'Menunggu',
    approved: 'Disetujui',
    rejected: 'Ditolak',
    paid: 'Dibayar',
    seniorApproved: 'Disetujui Manajemen Senior',
    
    // Leave Types
    annualLeave: 'Cuti Tahunan',
    sickLeave: 'Cuti Sakit',
    maternityLeave: 'Cuti Melahirkan',
    paternityLeave: 'Cuti Ayah',
    vacation: 'Liburan',
    emergencyLeave: 'Cuti Darurat',
    compassionateLeave: 'Cuti Duka',
    studyLeave: 'Cuti Belajar',
    unpaidLeave: 'Cuti Tanpa Gaji',
    
    // View Modes
    myRequests: 'Permintaan Saya',
    teamRequests: 'Permintaan Tim',
    allRequests: 'Semua Permintaan',
      myLeaveRequests: 'Permohonan Cuti Saya',
      teamLeaveRequests: 'Permohonan Cuti Tim',
      requests: 'permintaan',
      overlappingLeaveRequest: 'Permintaan Cuti Tumpang Tindih',
      overlappingLeaveDescription: 'Anda sudah memiliki permintaan cuti untuk tanggal-tanggal ini. Silakan pilih tanggal yang berbeda.',
      newRequest: 'Permintaan Baru',
      confirmDeleteLeave: 'Hapus Permintaan Cuti?',
      employee: 'Karyawan',
      actions: 'Tindakan',
    
    // Placeholders and Labels
    selectLeaveType: 'Pilih Jenis Cuti',
    selectCategory: 'Pilih Kategori',
    selectType: 'Pilih Jenis',
    selectStatus: 'Pilih Status',
    allTypes: 'Semua Jenis',
    allStatus: 'Semua Status',
    searchPlaceholder: 'Cari berdasarkan nama karyawan, alasan...',
    searchByEmployeeReason: 'Cari berdasarkan karyawan atau alasan...',
    selectDate: 'Pilih tanggal',
    submitLeaveRequestDescription: 'Kirim permintaan cuti baru untuk persetujuan',
    editRequestDescription: 'Edit detail permintaan cuti Anda',
    confirmDeleteDescription: 'Tindakan ini tidak dapat dibatalkan. Ini akan menghapus permintaan cuti Anda secara permanen.',
    seniorApprove: 'Persetujuan Senior',
    adminApprove: 'Persetujuan Admin',
    finalApprove: 'Persetujuan Final',
    noMatchingRequests: 'Tidak ada permintaan yang cocok dengan filter saat ini',
    clearFilters: 'Hapus Filter',
    noLeaveRequestsFound: 'Tidak ada permintaan cuti ditemukan',
    max: 'Maks',
    daysPerYear: 'hari/tahun',
    
    // Actions
    createRequest: 'Buat Permintaan',
    editRequest: 'Edit Permintaan',
    deleteRequest: 'Hapus Permintaan',
    confirmDelete: 'Konfirmasi Hapus',
    approveRequest: 'Setujui Permintaan',
    rejectRequest: 'Tolak Permintaan',
    update: 'Perbarui',
    bulkActions: 'Tindakan Massal',
    selectAll: 'Pilih Semua',
    deselectAll: 'Batalkan Pilihan',
    export: 'Ekspor',
    exportSuccess: 'Data berhasil diekspor',
    print: 'Cetak',
    
    // Messages
    success: 'Sukses',
    error: 'Error',
    warning: 'Peringatan',
    info: 'Info',
    loading: 'Memuat...',
    noData: 'Tidak Ada Data',
    noResults: 'Tidak Ada Hasil',
    
    // Categories
    general: 'Umum',
    travel: 'Perjalanan',
    meals: 'Makanan',
    supplies: 'Perlengkapan Kantor',
    equipment: 'Peralatan',
    training: 'Pelatihan',
    groceries: 'Bahan Makanan',
    others: 'Lainnya',
    
    // Transaction Types
    request: 'Permintaan',
    expense: 'Pengeluaran',
    reimbursement: 'Penggantian',
    
    // Cash Control
    cashControlTitle: 'Kontrol Kas',
    cashControlDescription: 'Kelola permintaan kas dan laporan pengeluaran',
    newTransaction: 'Transaksi Baru',
    cashRequest: 'Permintaan Kas',
    expenseReport: 'Laporan Pengeluaran',
    cashRequestTitle: 'Permintaan Kas',
    cashRequestDescription: 'Ajukan uang muka dari perusahaan',
    expenseReportTitle: 'Laporan Pengeluaran',
    expenseReportDescription: 'Ajukan laporan pengeluaran atau penggantian',
    amount: 'Jumlah',
    currency: 'Mata Uang',
    category: 'Kategori',
    description: 'Deskripsi',
    receipt: 'Tanda Terima',
    uploadReceipt: 'Unggah Tanda Terima',
    uploading: 'Mengunggah...',
    receiptUploaded: 'Tanda terima berhasil diunggah',
    enterReceiptUrl: 'Atau masukkan URL tanda terima secara manual',
    cashBalance: 'Saldo Kas',
    availableCashBalance: 'Saldo kas yang tersedia',
    credit: 'Kredit',
    debit: 'Debit',
    balance: 'Saldo',
    moneyReceived: 'Uang diterima',
    moneySpent: 'Uang dibelanjakan',
    netPosition: 'Posisi bersih',
    recentTransactions: 'Transaksi Terkini',
    manageCashRequests: 'Kelola permintaan kas dan laporan pengeluaran',
    yourCashHistory: 'Riwayat transaksi kas Anda',
    noTransactionsFound: 'Tidak ada transaksi ditemukan',
    affectsBalance: 'Mempengaruhi Saldo',
    rejectionReason: 'Alasan',
    reasonForRejection: 'Alasan penolakan:',
    cashRequestPlaceholder: 'Jelaskan mengapa Anda memerlukan uang muka ini...',
    cashRequestSuccess: 'Permintaan kas diajukan untuk persetujuan',
    expenseReportSuccess: 'Laporan pengeluaran berhasil diajukan',
    transactionApproved: 'Transaksi disetujui',
    transactionRejected: 'Transaksi ditolak',
    failedToApprove: 'Gagal menyetujui transaksi',
    failedToReject: 'Gagal menolak transaksi',
    failedToFetch: 'Gagal mengambil transaksi',
    failedToCreate: 'Gagal membuat permintaan kas',
    failedToSubmit: 'Gagal mengirim laporan pengeluaran',
    receiptUploadSuccess: 'Tanda terima berhasil diunggah',
    receiptUploadError: 'Gagal mengunggah tanda terima',
    officeSupplies: 'Perlengkapan Kantor',
    
    // Authentication
    signIn: 'Masuk',
    signOut: 'Keluar',
    signUp: 'Daftar',
    password: 'Kata Sandi',
    confirmPassword: 'Konfirmasi Kata Sandi',
    forgotPassword: 'Lupa Kata Sandi',
    resetPassword: 'Reset Kata Sandi',
    
    // Profile page
    myProfile: 'Profil Saya',
    personalInformation: 'Informasi Pribadi',
    editProfile: 'Edit Profil',
    cancelEdit: 'Batal',
    firstName: 'Nama Depan',
    lastName: 'Nama Belakang',
    email: 'Email',
    employeeId: 'ID Karyawan',
    department: 'Departemen',
    position: 'Posisi',
    phoneNumber: 'Nomor Telepon',
    dateOfBirth: 'Tanggal Lahir',
    idNumber: 'Nomor ID',
    passportNumber: 'Nomor Paspor',
    visaNumber: 'Nomor Visa',
    maritalStatus: 'Status Pernikahan',
    emergencyContactName: 'Nama Kontak Darurat',
    emergencyContactPhone: 'Telepon Kontak Darurat',
    homeAddress: 'Alamat Rumah',
    selectDepartment: 'Pilih departemen',
    saveChanges: 'Simpan Perubahan',
    saving: 'Menyimpan...',
    accountCreated: 'Akun Dibuat',
    leaveBalances: 'Saldo Cuti',
    report: 'Laporan',
    comingSoon: 'Segera Hadir',
    reportFeatureComingSoon: 'Fitur pembuatan laporan akan segera tersedia. Anda akan dapat mengunduh laporan PDF terperinci tentang saldo cuti Anda.',
    initialAllocation: 'Alokasi awal',
    daysYear: 'hari/tahun',
    used: 'Digunakan',
    available: 'Tersedia',
    noLeaveBalances: 'Tidak ada saldo cuti yang dikonfigurasi untuk tahun ini',
    profileNotFound: 'Profil tidak ditemukan',
    profileUpdateSuccess: 'Profil berhasil diperbarui',
    profileUpdateError: 'Gagal memperbarui profil',
    managePersonalInfo: 'Kelola informasi pribadi Anda dan lihat saldo cuti',
    personalDetails: 'Rincian Pribadi',
    requestChange: 'Minta Perubahan',
    accountEmailLogin: 'Email Akun (Login)',
    enterLastName: 'Masukkan nama belakang',
    enterEmailAddress: 'Masukkan alamat email',
    enterEmployeeId: 'Masukkan ID karyawan',
    selectDepartmentPlaceholder: 'Pilih departemen',
    enterPosition: 'Masukkan posisi/jabatan',
    enterPhoneNumber: 'Masukkan nomor telepon atau NIL jika tidak berlaku',
    enterDateOfBirth: 'Masukkan tanggal lahir atau NIL jika tidak berlaku',
    enterIdNumber: 'Masukkan nomor ID atau NIL jika tidak berlaku',
    enterPassportNumber: 'Masukkan nomor paspor atau NIL jika tidak berlaku',
    enterVisaNumber: 'Masukkan nomor visa atau NIL jika tidak berlaku',
    selectMaritalStatus: 'Pilih status pernikahan',
    enterEmergencyContactName: 'Masukkan nama kontak darurat atau NIL jika tidak berlaku',
    enterEmergencyContactPhone: 'Masukkan telepon kontak darurat atau NIL jika tidak berlaku',
    enterHomeAddress: 'Masukkan alamat rumah atau NIL jika tidak berlaku',
    notProvided: 'Tidak tersedia',
    submitRequest: 'Kirim Permohonan',
    requestProfileChange: 'Minta Perubahan Profil',
    submitRequestDescription: 'Kirim permohonan untuk mengubah informasi profil yang memerlukan persetujuan.',
    selectFieldToChange: 'Pilih bidang yang akan diubah',
    selectField: 'Pilih bidang',
    enterNewValue: 'Masukkan nilai baru',
    fromTo: 'Dari: "{from}" → Ke: "{to}"',
    
    // Documents
    documents: 'Dokumen',
    uploadDocument: 'Unggah Dokumen',
    uploadDocumentDescription: 'Unggah dokumen baru untuk profil ini',
    documentType: 'Jenis Dokumen',
    selectDocumentType: 'Pilih jenis dokumen',
    file: 'File',
    selected: 'Dipilih',
    documentUploaded: 'Dokumen berhasil diunggah',
    documentDeleted: 'Dokumen berhasil dihapus',
    deleteDocument: 'Hapus Dokumen',
    deleteDocumentConfirm: 'Apakah Anda yakin ingin menghapus dokumen ini? Tindakan ini tidak dapat dibatalkan.',
    noDocuments: 'Belum ada dokumen yang diunggah',
    passport: 'Paspor',
    idCard: 'Kartu Identitas',
    visa: 'Visa',
    certificate: 'Sertifikat',
    contract: 'Kontrak',
    document: 'Dokumen',
    
    // Leave Management
    leaveRequest: 'Cuti',
    createLeaveRequest: 'Buat Permohonan Cuti',
    submitLeaveRequest: 'Kirim Permohonan Cuti',
    duration: 'Durasi',
    day: 'Hari',
    days: 'Hari',
    reasonOptional: 'Alasan (Opsional)',
    reasonPlaceholder: 'Silakan berikan alasan untuk permohonan cuti Anda...',
    requestSummary: 'Ringkasan Permohonan',
    submitting: 'Mengirim...',
    requestSubmitted: 'Permohonan cuti berhasil dikirim',
    requestUpdated: 'Permohonan cuti berhasil diperbarui',
    requestDeleted: 'Permohonan cuti berhasil dihapus',
    endDateBeforeStart: 'Tanggal berakhir tidak boleh sebelum tanggal mulai',
    overlappingDates: 'Tanggal cuti bertumpang tindih dengan permohonan yang sudah ada',
    requiredField: 'Harap isi semua field yang wajib diisi',
    operationFailed: 'Operasi gagal',
    
    // Department translations
    humanResources: 'Sumber Daya Manusia',
    engineering: 'Teknik',
    marketing: 'Pemasaran',
    sales: 'Penjualan',
    finance: 'Keuangan',
    operations: 'Operasional',
    customerSupport: 'Dukungan Pelanggan',
    product: 'Produk',
    legal: 'Hukum',
    domesticHelper: 'Asisten Rumah Tangga',
    unknown: 'Tidak Diketahui',
    
    // Common actions
    add: 'Tambah',
    clear: 'Bersihkan',
    search: 'Cari',
    type: 'Jenis',
    requestStatus: 'Status permintaan',
    
    // Calendar
    leaveCalendarDescription: 'Lihat dan kelola permohonan cuti di kalender',
    calendarView: 'Tampilan Kalender',
    colorLegend: 'Legenda Warna',
    myLeave: 'Cuti Saya',
    teamLeave: 'Cuti Tim',
    allLeave: 'Semua Cuti',
    leaveAllocationManagement: 'Manajemen Alokasi Cuti',
    showRestDays: 'Tampilkan hari istirahat',
    showPublicHolidays: 'Tampilkan hari libur umum',
    restDays: 'Hari Istirahat',
    publicHolidays: 'Hari Libur Umum',

    // Tugas
    manageTasks: 'Kelola tugas dan penugasan',
    createTask: 'Buat Tugas',
    selectTeamMember: 'Pilih anggota tim',
    noTasksFound: 'Tidak ada tugas ditemukan',
    start: 'Mulai',
    complete: 'Selesai',

    // Status Tugas
    inProgress: 'Sedang berlangsung',
    completed: 'Selesai',
    cancelled: 'Dibatalkan',

    // Prioritas
    low: 'Rendah',
    medium: 'Sedang',
    high: 'Tinggi',
    urgent: 'Mendesak',
    
    // Peran
    roleEmployee: 'Karyawan',
    roleHrAdmin: 'Admin SDM',
    roleAdministrator: 'Administrator',
    roleManager: 'Manajer',
    
    // Settings Page
    administratorSettings: 'Pengaturan Administrator',
    manageSystemSettings: 'Kelola pengaturan sistem dan delegasi peran',
    delegation: 'Delegasi',
    leaveManagement: 'Manajemen Cuti',
    workSchedules: 'Jadwal Kerja',
    storageCentre: 'Pusat Penyimpanan',
    
    // Delegation Settings
    delegationManagement: 'Manajemen Delegasi',
    seniorManagementDelegation: 'Delegasi Manajemen Senior',
    delegationDescription: 'Jika diaktifkan, Manajemen Senior dapat melakukan persetujuan akhir untuk permintaan cuti dan alokasi tanpa memerlukan konfirmasi Administrator.',
    roleHierarchyPermissions: 'Hierarki & Izin Peran',
    administratorCompanyOwner: 'Administrator / Pemilik Perusahaan',
    highestAuthority: 'Otoritas tertinggi dengan akses tidak terbatas ke semua modul sistem dan data',
    seniorManagementHRGM: 'Manajemen Senior (SDM/GM)',
    firstLineExecutor: 'Eksekutor lini pertama untuk proses karyawan, mengelola orientasi dan alur persetujuan',
    twoTierApprovalSystem: 'Sistem Persetujuan Dua Tingkat',
    leaveAllocationsRequire: 'Alokasi cuti memerlukan persetujuan Manajemen Senior terlebih dahulu, kemudian konfirmasi Administrator',
    leaveRequestsFollow: 'Permintaan cuti mengikuti alur persetujuan ganda yang sama',
    administratorCanDelegate: 'Administrator dapat mendelegasikan hak persetujuan akhir kepada Manajemen Senior',
    administratorRetains: 'Administrator mempertahankan hak untuk meninjau dan membatalkan keputusan apa pun',
    hrAdminRoleManagement: 'Manajemen Peran Admin SDM',
    currentHRAdministrators: 'Administrator SDM Saat Ini',
    noHRAdminsAssigned: 'Tidak ada Admin SDM yang ditugaskan',
    demoteToEmployee: 'Turunkan ke Karyawan',
    promoteEmployeeToHRAdmin: 'Promosikan Karyawan ke Admin SDM',
    selectAnEmployee: 'Pilih karyawan...',
    promoteToHRAdmin: 'Promosikan ke Admin SDM',
    delegationEnabledSuccess: 'Delegasi berhasil diaktifkan',
    delegationDisabledSuccess: 'Delegasi berhasil dinonaktifkan',
    employeePromotedSuccess: 'Karyawan berhasil dipromosikan menjadi Admin SDM',
    hrAdminDemotedSuccess: 'Admin SDM berhasil diturunkan menjadi Karyawan',
    failedToFetchDelegationSettings: 'Gagal mengambil pengaturan delegasi',
    failedToUpdateDelegationSettings: 'Gagal memperbarui pengaturan delegasi',
    failedToFetchHRAdmins: 'Gagal mengambil admin SDM',
    failedToFetchEmployees: 'Gagal mengambil karyawan',
    failedToPromoteEmployee: 'Gagal mempromosikan karyawan',
    failedToDemoteHRAdmin: 'Gagal menurunkan admin SDM',
    onlyHRAdminsCanManage: 'Hanya Admin SDM dan Administrator yang dapat mengelola pengaturan delegasi.'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'zh-TW', 'zh-CN', 'id'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const dict = translations[language] || translations['en'];
    return (dict[key as keyof typeof dict] as string) || (translations['en'][key as keyof typeof translations['en']] as string) || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};