// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cavrkwzwlgrstddykpsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdnJrd3p3bGdyc3RkZHlrcHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODc2NjcsImV4cCI6MjA3MjQ2MzY2N30.Yv9EHJO9eCt7TfogrGuxoJQGAaCntvSVBVAL8rp5qUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});